// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: sys_tenant_package.proto

// sys_tenant_package 租户套餐

package tenant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysTenantPackageService_SysTenantPackageCreate_FullMethodName    = "/tenant.SysTenantPackageService/SysTenantPackageCreate"
	SysTenantPackageService_SysTenantPackageUpdate_FullMethodName    = "/tenant.SysTenantPackageService/SysTenantPackageUpdate"
	SysTenantPackageService_SysTenantPackageDelete_FullMethodName    = "/tenant.SysTenantPackageService/SysTenantPackageDelete"
	SysTenantPackageService_SysTenantPackage_FullMethodName          = "/tenant.SysTenantPackageService/SysTenantPackage"
	SysTenantPackageService_SysTenantPackageList_FullMethodName      = "/tenant.SysTenantPackageService/SysTenantPackageList"
	SysTenantPackageService_SysTenantPackageListTotal_FullMethodName = "/tenant.SysTenantPackageService/SysTenantPackageListTotal"
)

// SysTenantPackageServiceClient is the client API for SysTenantPackageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysTenantPackageService 服务
type SysTenantPackageServiceClient interface {
	SysTenantPackageCreate(ctx context.Context, in *SysTenantPackageCreateRequest, opts ...grpc.CallOption) (*SysTenantPackageCreateResponse, error)
	SysTenantPackageUpdate(ctx context.Context, in *SysTenantPackageUpdateRequest, opts ...grpc.CallOption) (*SysTenantPackageUpdateResponse, error)
	SysTenantPackageDelete(ctx context.Context, in *SysTenantPackageDeleteRequest, opts ...grpc.CallOption) (*SysTenantPackageDeleteResponse, error)
	SysTenantPackage(ctx context.Context, in *SysTenantPackageRequest, opts ...grpc.CallOption) (*SysTenantPackageResponse, error)
	SysTenantPackageList(ctx context.Context, in *SysTenantPackageListRequest, opts ...grpc.CallOption) (*SysTenantPackageListResponse, error)
	SysTenantPackageListTotal(ctx context.Context, in *SysTenantPackageListTotalRequest, opts ...grpc.CallOption) (*SysTenantPackageTotalResponse, error)
}

type sysTenantPackageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysTenantPackageServiceClient(cc grpc.ClientConnInterface) SysTenantPackageServiceClient {
	return &sysTenantPackageServiceClient{cc}
}

func (c *sysTenantPackageServiceClient) SysTenantPackageCreate(ctx context.Context, in *SysTenantPackageCreateRequest, opts ...grpc.CallOption) (*SysTenantPackageCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageCreateResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackageCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysTenantPackageServiceClient) SysTenantPackageUpdate(ctx context.Context, in *SysTenantPackageUpdateRequest, opts ...grpc.CallOption) (*SysTenantPackageUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageUpdateResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackageUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysTenantPackageServiceClient) SysTenantPackageDelete(ctx context.Context, in *SysTenantPackageDeleteRequest, opts ...grpc.CallOption) (*SysTenantPackageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageDeleteResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysTenantPackageServiceClient) SysTenantPackage(ctx context.Context, in *SysTenantPackageRequest, opts ...grpc.CallOption) (*SysTenantPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysTenantPackageServiceClient) SysTenantPackageList(ctx context.Context, in *SysTenantPackageListRequest, opts ...grpc.CallOption) (*SysTenantPackageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageListResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysTenantPackageServiceClient) SysTenantPackageListTotal(ctx context.Context, in *SysTenantPackageListTotalRequest, opts ...grpc.CallOption) (*SysTenantPackageTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysTenantPackageTotalResponse)
	err := c.cc.Invoke(ctx, SysTenantPackageService_SysTenantPackageListTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysTenantPackageServiceServer is the server API for SysTenantPackageService service.
// All implementations must embed UnimplementedSysTenantPackageServiceServer
// for forward compatibility.
//
// SysTenantPackageService 服务
type SysTenantPackageServiceServer interface {
	SysTenantPackageCreate(context.Context, *SysTenantPackageCreateRequest) (*SysTenantPackageCreateResponse, error)
	SysTenantPackageUpdate(context.Context, *SysTenantPackageUpdateRequest) (*SysTenantPackageUpdateResponse, error)
	SysTenantPackageDelete(context.Context, *SysTenantPackageDeleteRequest) (*SysTenantPackageDeleteResponse, error)
	SysTenantPackage(context.Context, *SysTenantPackageRequest) (*SysTenantPackageResponse, error)
	SysTenantPackageList(context.Context, *SysTenantPackageListRequest) (*SysTenantPackageListResponse, error)
	SysTenantPackageListTotal(context.Context, *SysTenantPackageListTotalRequest) (*SysTenantPackageTotalResponse, error)
	mustEmbedUnimplementedSysTenantPackageServiceServer()
}

// UnimplementedSysTenantPackageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysTenantPackageServiceServer struct{}

func (UnimplementedSysTenantPackageServiceServer) SysTenantPackageCreate(context.Context, *SysTenantPackageCreateRequest) (*SysTenantPackageCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackageCreate not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) SysTenantPackageUpdate(context.Context, *SysTenantPackageUpdateRequest) (*SysTenantPackageUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackageUpdate not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) SysTenantPackageDelete(context.Context, *SysTenantPackageDeleteRequest) (*SysTenantPackageDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackageDelete not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) SysTenantPackage(context.Context, *SysTenantPackageRequest) (*SysTenantPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackage not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) SysTenantPackageList(context.Context, *SysTenantPackageListRequest) (*SysTenantPackageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackageList not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) SysTenantPackageListTotal(context.Context, *SysTenantPackageListTotalRequest) (*SysTenantPackageTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysTenantPackageListTotal not implemented")
}
func (UnimplementedSysTenantPackageServiceServer) mustEmbedUnimplementedSysTenantPackageServiceServer() {
}
func (UnimplementedSysTenantPackageServiceServer) testEmbeddedByValue() {}

// UnsafeSysTenantPackageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysTenantPackageServiceServer will
// result in compilation errors.
type UnsafeSysTenantPackageServiceServer interface {
	mustEmbedUnimplementedSysTenantPackageServiceServer()
}

func RegisterSysTenantPackageServiceServer(s grpc.ServiceRegistrar, srv SysTenantPackageServiceServer) {
	// If the following call panics, it indicates UnimplementedSysTenantPackageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysTenantPackageService_ServiceDesc, srv)
}

func _SysTenantPackageService_SysTenantPackageCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackageCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageCreate(ctx, req.(*SysTenantPackageCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysTenantPackageService_SysTenantPackageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackageUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageUpdate(ctx, req.(*SysTenantPackageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysTenantPackageService_SysTenantPackageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageDelete(ctx, req.(*SysTenantPackageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysTenantPackageService_SysTenantPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackage(ctx, req.(*SysTenantPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysTenantPackageService_SysTenantPackageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageList(ctx, req.(*SysTenantPackageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysTenantPackageService_SysTenantPackageListTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysTenantPackageListTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageListTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysTenantPackageService_SysTenantPackageListTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysTenantPackageServiceServer).SysTenantPackageListTotal(ctx, req.(*SysTenantPackageListTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysTenantPackageService_ServiceDesc is the grpc.ServiceDesc for SysTenantPackageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysTenantPackageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.SysTenantPackageService",
	HandlerType: (*SysTenantPackageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysTenantPackageCreate",
			Handler:    _SysTenantPackageService_SysTenantPackageCreate_Handler,
		},
		{
			MethodName: "SysTenantPackageUpdate",
			Handler:    _SysTenantPackageService_SysTenantPackageUpdate_Handler,
		},
		{
			MethodName: "SysTenantPackageDelete",
			Handler:    _SysTenantPackageService_SysTenantPackageDelete_Handler,
		},
		{
			MethodName: "SysTenantPackage",
			Handler:    _SysTenantPackageService_SysTenantPackage_Handler,
		},
		{
			MethodName: "SysTenantPackageList",
			Handler:    _SysTenantPackageService_SysTenantPackageList_Handler,
		},
		{
			MethodName: "SysTenantPackageListTotal",
			Handler:    _SysTenantPackageService_SysTenantPackageListTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_tenant_package.proto",
}
