// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: dict.proto

// dict 字典

package dict

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DictObject 数据对象
type DictObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:sort" json:"sort"
	Sort *int32 `protobuf:"varint,2,opt,name=sort,proto3,oneof" json:"sort" gorm:"column:sort"` //排序
	// @inject_tag: gorm:"column:label" json:"label"
	Label *string `protobuf:"bytes,3,opt,name=label,proto3,oneof" json:"label" gorm:"column:label"` //标签
	// @inject_tag: gorm:"column:value" json:"value"
	Value *string `protobuf:"bytes,4,opt,name=value,proto3,oneof" json:"value" gorm:"column:value"` //键值
	// @inject_tag: gorm:"column:dict_type" json:"dictType"
	DictType *string `protobuf:"bytes,5,opt,name=dict_type,json=dictType,proto3,oneof" json:"dictType" gorm:"column:dict_type"` //字典类型
	// @inject_tag: gorm:"column:color_type" json:"colorType"
	ColorType *string `protobuf:"bytes,6,opt,name=color_type,json=colorType,proto3,oneof" json:"colorType" gorm:"column:color_type"` //颜色类型
	// @inject_tag: gorm:"column:css_class" json:"cssClass"
	CssClass *string `protobuf:"bytes,7,opt,name=css_class,json=cssClass,proto3,oneof" json:"cssClass" gorm:"column:css_class"` //CSS样式
	// @inject_tag: gorm:"column:status" json:"status"
	Status *int32 `protobuf:"varint,8,opt,name=status,proto3,oneof" json:"status" gorm:"column:status"` //状态:0正常/1停用
	// @inject_tag: gorm:"column:remark" json:"remark"
	Remark *string `protobuf:"bytes,9,opt,name=remark,proto3,oneof" json:"remark" gorm:"column:remark"` //备注
	// @inject_tag: gorm:"column:creator" json:"creator"
	Creator *string `protobuf:"bytes,10,opt,name=creator,proto3,oneof" json:"creator" gorm:"column:creator"` //创建人
	// @inject_tag: gorm:"column:create_time" json:"createTime"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"createTime" gorm:"column:create_time"` //创建时间
	// @inject_tag: gorm:"column:updater" json:"updater"
	Updater *string `protobuf:"bytes,12,opt,name=updater,proto3,oneof" json:"updater" gorm:"column:updater"` //更新人
	// @inject_tag: gorm:"column:update_time" json:"updateTime"
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"updateTime" gorm:"column:update_time"` //更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictObject) Reset() {
	*x = DictObject{}
	mi := &file_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictObject) ProtoMessage() {}

func (x *DictObject) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictObject.ProtoReflect.Descriptor instead.
func (*DictObject) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{0}
}

func (x *DictObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DictObject) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *DictObject) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *DictObject) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *DictObject) GetDictType() string {
	if x != nil && x.DictType != nil {
		return *x.DictType
	}
	return ""
}

func (x *DictObject) GetColorType() string {
	if x != nil && x.ColorType != nil {
		return *x.ColorType
	}
	return ""
}

func (x *DictObject) GetCssClass() string {
	if x != nil && x.CssClass != nil {
		return *x.CssClass
	}
	return ""
}

func (x *DictObject) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *DictObject) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *DictObject) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *DictObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *DictObject) GetUpdater() string {
	if x != nil && x.Updater != nil {
		return *x.Updater
	}
	return ""
}

func (x *DictObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// DictTotalResponse 列表数据总量
type DictTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTotalResponse) Reset() {
	*x = DictTotalResponse{}
	mi := &file_dict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTotalResponse) ProtoMessage() {}

func (x *DictTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTotalResponse.ProtoReflect.Descriptor instead.
func (*DictTotalResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{1}
}

func (x *DictTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DictTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// DictCreateRequest 创建数据请求
type DictCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DictObject            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictCreateRequest) Reset() {
	*x = DictCreateRequest{}
	mi := &file_dict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictCreateRequest) ProtoMessage() {}

func (x *DictCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictCreateRequest.ProtoReflect.Descriptor instead.
func (*DictCreateRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{2}
}

func (x *DictCreateRequest) GetData() *DictObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// DictCreateResponse 创建数据响应
type DictCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictCreateResponse) Reset() {
	*x = DictCreateResponse{}
	mi := &file_dict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictCreateResponse) ProtoMessage() {}

func (x *DictCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictCreateResponse.ProtoReflect.Descriptor instead.
func (*DictCreateResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{3}
}

func (x *DictCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DictCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// DictUpdateRequest 更新数据请求
type DictUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *DictObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictUpdateRequest) Reset() {
	*x = DictUpdateRequest{}
	mi := &file_dict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictUpdateRequest) ProtoMessage() {}

func (x *DictUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictUpdateRequest.ProtoReflect.Descriptor instead.
func (*DictUpdateRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{4}
}

func (x *DictUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictUpdateRequest) GetData() *DictObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// DictUpdateResponse 更新数据响应
type DictUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictUpdateResponse) Reset() {
	*x = DictUpdateResponse{}
	mi := &file_dict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictUpdateResponse) ProtoMessage() {}

func (x *DictUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictUpdateResponse.ProtoReflect.Descriptor instead.
func (*DictUpdateResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{5}
}

func (x *DictUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// DictDeleteRequest 删除数据请求
type DictDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictDeleteRequest) Reset() {
	*x = DictDeleteRequest{}
	mi := &file_dict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictDeleteRequest) ProtoMessage() {}

func (x *DictDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictDeleteRequest.ProtoReflect.Descriptor instead.
func (*DictDeleteRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{6}
}

func (x *DictDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DictDeleteResponse 删除数据响应
type DictDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictDeleteResponse) Reset() {
	*x = DictDeleteResponse{}
	mi := &file_dict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictDeleteResponse) ProtoMessage() {}

func (x *DictDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictDeleteResponse.ProtoReflect.Descriptor instead.
func (*DictDeleteResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{7}
}

func (x *DictDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// DictRequest 查询单条数据请求
type DictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictRequest) Reset() {
	*x = DictRequest{}
	mi := &file_dict_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictRequest) ProtoMessage() {}

func (x *DictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictRequest.ProtoReflect.Descriptor instead.
func (*DictRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{8}
}

func (x *DictRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DictResponse 查询单条数据响应
type DictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *DictObject            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictResponse) Reset() {
	*x = DictResponse{}
	mi := &file_dict_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResponse) ProtoMessage() {}

func (x *DictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResponse.ProtoReflect.Descriptor instead.
func (*DictResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{9}
}

func (x *DictResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DictResponse) GetData() *DictObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// DictListRequest 列表数据
type DictListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"dict_type" json:"dictType"
	DictType *string `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3,oneof" json:"dictType" db:"dict_type"` // 字典类型
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictListRequest) Reset() {
	*x = DictListRequest{}
	mi := &file_dict_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictListRequest) ProtoMessage() {}

func (x *DictListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictListRequest.ProtoReflect.Descriptor instead.
func (*DictListRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{10}
}

func (x *DictListRequest) GetDictType() string {
	if x != nil && x.DictType != nil {
		return *x.DictType
	}
	return ""
}

func (x *DictListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *DictListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// DictListResponse 数据响应
type DictListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*DictObject          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictListResponse) Reset() {
	*x = DictListResponse{}
	mi := &file_dict_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictListResponse) ProtoMessage() {}

func (x *DictListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictListResponse.ProtoReflect.Descriptor instead.
func (*DictListResponse) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{11}
}

func (x *DictListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DictListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DictListResponse) GetData() []*DictObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// DictListTotalRequest 列表数据
type DictListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"dict_type" json:"dictType"
	DictType *string `protobuf:"bytes,1,opt,name=dict_type,json=dictType,proto3,oneof" json:"dictType" db:"dict_type"` // 字典类型
	// @inject_tag: db:"status" json:"status"
	Status        *int32 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictListTotalRequest) Reset() {
	*x = DictListTotalRequest{}
	mi := &file_dict_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictListTotalRequest) ProtoMessage() {}

func (x *DictListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dict_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictListTotalRequest.ProtoReflect.Descriptor instead.
func (*DictListTotalRequest) Descriptor() ([]byte, []int) {
	return file_dict_proto_rawDescGZIP(), []int{12}
}

func (x *DictListTotalRequest) GetDictType() string {
	if x != nil && x.DictType != nil {
		return *x.DictType
	}
	return ""
}

func (x *DictListTotalRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

var File_dict_proto protoreflect.FileDescriptor

const file_dict_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dict.proto\x12\x04dict\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"\xc7\x04\n" +
	"\n" +
	"DictObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x02 \x01(\x05H\x01R\x04sort\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\x03 \x01(\tH\x02R\x05label\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x04 \x01(\tH\x03R\x05value\x88\x01\x01\x12 \n" +
	"\tdict_type\x18\x05 \x01(\tH\x04R\bdictType\x88\x01\x01\x12\"\n" +
	"\n" +
	"color_type\x18\x06 \x01(\tH\x05R\tcolorType\x88\x01\x01\x12 \n" +
	"\tcss_class\x18\a \x01(\tH\x06R\bcssClass\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\x05H\aR\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\t \x01(\tH\bR\x06remark\x88\x01\x01\x12\x1d\n" +
	"\acreator\x18\n" +
	" \x01(\tH\tR\acreator\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1d\n" +
	"\aupdater\x18\f \x01(\tH\n" +
	"R\aupdater\x88\x01\x01\x12;\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_sortB\b\n" +
	"\x06_labelB\b\n" +
	"\x06_valueB\f\n" +
	"\n" +
	"_dict_typeB\r\n" +
	"\v_color_typeB\f\n" +
	"\n" +
	"_css_classB\t\n" +
	"\a_statusB\t\n" +
	"\a_remarkB\n" +
	"\n" +
	"\b_creatorB\n" +
	"\n" +
	"\b_updater\"M\n" +
	"\x11DictTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"9\n" +
	"\x11DictCreateRequest\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.dict.DictObjectR\x04data\"N\n" +
	"\x12DictCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"I\n" +
	"\x11DictUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.dict.DictObjectR\x04data\":\n" +
	"\x12DictUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"#\n" +
	"\x11DictDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x12DictDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1d\n" +
	"\vDictRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"Z\n" +
	"\fDictResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12$\n" +
	"\x04data\x18\x03 \x01(\v2\x10.dict.DictObjectR\x04data\"\xbc\x01\n" +
	"\x0fDictListRequest\x12 \n" +
	"\tdict_type\x18\x01 \x01(\tH\x00R\bdictType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x01R\x06status\x88\x01\x01\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.pagination.PaginationRequestH\x02R\n" +
	"pagination\x88\x01\x01B\f\n" +
	"\n" +
	"_dict_typeB\t\n" +
	"\a_statusB\r\n" +
	"\v_pagination\"^\n" +
	"\x10DictListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.dict.DictObjectR\x04data\"n\n" +
	"\x14DictListTotalRequest\x12 \n" +
	"\tdict_type\x18\x01 \x01(\tH\x00R\bdictType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x01R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_dict_typeB\t\n" +
	"\a_status2\x80\x03\n" +
	"\vDictService\x12?\n" +
	"\n" +
	"DictCreate\x12\x17.dict.DictCreateRequest\x1a\x18.dict.DictCreateResponse\x12?\n" +
	"\n" +
	"DictUpdate\x12\x17.dict.DictUpdateRequest\x1a\x18.dict.DictUpdateResponse\x12?\n" +
	"\n" +
	"DictDelete\x12\x17.dict.DictDeleteRequest\x1a\x18.dict.DictDeleteResponse\x12-\n" +
	"\x04Dict\x12\x11.dict.DictRequest\x1a\x12.dict.DictResponse\x129\n" +
	"\bDictList\x12\x15.dict.DictListRequest\x1a\x16.dict.DictListResponse\x12D\n" +
	"\rDictListTotal\x12\x1a.dict.DictListTotalRequest\x1a\x17.dict.DictTotalResponseB\x19Z\x17cloud/service/dict;dictb\x06proto3"

var (
	file_dict_proto_rawDescOnce sync.Once
	file_dict_proto_rawDescData []byte
)

func file_dict_proto_rawDescGZIP() []byte {
	file_dict_proto_rawDescOnce.Do(func() {
		file_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dict_proto_rawDesc), len(file_dict_proto_rawDesc)))
	})
	return file_dict_proto_rawDescData
}

var file_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dict_proto_goTypes = []any{
	(*DictObject)(nil),                   // 0: dict.DictObject
	(*DictTotalResponse)(nil),            // 1: dict.DictTotalResponse
	(*DictCreateRequest)(nil),            // 2: dict.DictCreateRequest
	(*DictCreateResponse)(nil),           // 3: dict.DictCreateResponse
	(*DictUpdateRequest)(nil),            // 4: dict.DictUpdateRequest
	(*DictUpdateResponse)(nil),           // 5: dict.DictUpdateResponse
	(*DictDeleteRequest)(nil),            // 6: dict.DictDeleteRequest
	(*DictDeleteResponse)(nil),           // 7: dict.DictDeleteResponse
	(*DictRequest)(nil),                  // 8: dict.DictRequest
	(*DictResponse)(nil),                 // 9: dict.DictResponse
	(*DictListRequest)(nil),              // 10: dict.DictListRequest
	(*DictListResponse)(nil),             // 11: dict.DictListResponse
	(*DictListTotalRequest)(nil),         // 12: dict.DictListTotalRequest
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
	(*pagination.PaginationRequest)(nil), // 14: pagination.PaginationRequest
}
var file_dict_proto_depIdxs = []int32{
	13, // 0: dict.DictObject.create_time:type_name -> google.protobuf.Timestamp
	13, // 1: dict.DictObject.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: dict.DictCreateRequest.data:type_name -> dict.DictObject
	0,  // 3: dict.DictUpdateRequest.data:type_name -> dict.DictObject
	0,  // 4: dict.DictResponse.data:type_name -> dict.DictObject
	14, // 5: dict.DictListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 6: dict.DictListResponse.data:type_name -> dict.DictObject
	2,  // 7: dict.DictService.DictCreate:input_type -> dict.DictCreateRequest
	4,  // 8: dict.DictService.DictUpdate:input_type -> dict.DictUpdateRequest
	6,  // 9: dict.DictService.DictDelete:input_type -> dict.DictDeleteRequest
	8,  // 10: dict.DictService.Dict:input_type -> dict.DictRequest
	10, // 11: dict.DictService.DictList:input_type -> dict.DictListRequest
	12, // 12: dict.DictService.DictListTotal:input_type -> dict.DictListTotalRequest
	3,  // 13: dict.DictService.DictCreate:output_type -> dict.DictCreateResponse
	5,  // 14: dict.DictService.DictUpdate:output_type -> dict.DictUpdateResponse
	7,  // 15: dict.DictService.DictDelete:output_type -> dict.DictDeleteResponse
	9,  // 16: dict.DictService.Dict:output_type -> dict.DictResponse
	11, // 17: dict.DictService.DictList:output_type -> dict.DictListResponse
	1,  // 18: dict.DictService.DictListTotal:output_type -> dict.DictTotalResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_dict_proto_init() }
func file_dict_proto_init() {
	if File_dict_proto != nil {
		return
	}
	file_dict_proto_msgTypes[0].OneofWrappers = []any{}
	file_dict_proto_msgTypes[10].OneofWrappers = []any{}
	file_dict_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dict_proto_rawDesc), len(file_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dict_proto_goTypes,
		DependencyIndexes: file_dict_proto_depIdxs,
		MessageInfos:      file_dict_proto_msgTypes,
	}.Build()
	File_dict_proto = out.File
	file_dict_proto_goTypes = nil
	file_dict_proto_depIdxs = nil
}
