// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: tenant.proto

// tenant 租户

package tenant

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantObject 数据对象
type TenantObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:name" json:"name"
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name" gorm:"column:name"` //名称
	// @inject_tag: gorm:"column:user_id" json:"userId"
	UserId *int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3,oneof" json:"userId" gorm:"column:user_id"` //用户
	// @inject_tag: gorm:"column:contact_name" json:"contactName"
	ContactName *string `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3,oneof" json:"contactName" gorm:"column:contact_name"` //联系人
	// @inject_tag: gorm:"column:contact_mobile" json:"contactMobile"
	ContactMobile *string `protobuf:"bytes,5,opt,name=contact_mobile,json=contactMobile,proto3,oneof" json:"contactMobile" gorm:"column:contact_mobile"` //联系电话
	// @inject_tag: gorm:"column:expire_date" json:"expireDate"
	ExpireDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expire_date,json=expireDate,proto3" json:"expireDate" gorm:"column:expire_date"` //过期时间
	// @inject_tag: gorm:"column:account_total" json:"accountTotal"
	AccountTotal *int64 `protobuf:"varint,7,opt,name=account_total,json=accountTotal,proto3,oneof" json:"accountTotal" gorm:"column:account_total"` //账号数量
	// @inject_tag: gorm:"column:package_id" json:"packageId"
	PackageId *int64 `protobuf:"varint,8,opt,name=package_id,json=packageId,proto3,oneof" json:"packageId" gorm:"column:package_id"` //套餐编号
	// @inject_tag: gorm:"column:status" json:"status"
	Status *int32 `protobuf:"varint,9,opt,name=status,proto3,oneof" json:"status" gorm:"column:status"` //状态:0正常/1停用
	// @inject_tag: gorm:"column:deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,10,opt,name=deleted,proto3,oneof" json:"deleted" gorm:"column:deleted"` //删除:0否/1是
	// @inject_tag: gorm:"column:creator" json:"creator"
	Creator *string `protobuf:"bytes,11,opt,name=creator,proto3,oneof" json:"creator" gorm:"column:creator"` //创建人
	// @inject_tag: gorm:"column:create_time" json:"createTime"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"createTime" gorm:"column:create_time"` //创建时间
	// @inject_tag: gorm:"column:updater" json:"updater"
	Updater *string `protobuf:"bytes,13,opt,name=updater,proto3,oneof" json:"updater" gorm:"column:updater"` //更新人
	// @inject_tag: gorm:"column:update_time" json:"updateTime"
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=update_time,json=updateTime,proto3" json:"updateTime" gorm:"column:update_time"` //更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantObject) Reset() {
	*x = TenantObject{}
	mi := &file_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantObject) ProtoMessage() {}

func (x *TenantObject) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantObject.ProtoReflect.Descriptor instead.
func (*TenantObject) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TenantObject) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TenantObject) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *TenantObject) GetContactName() string {
	if x != nil && x.ContactName != nil {
		return *x.ContactName
	}
	return ""
}

func (x *TenantObject) GetContactMobile() string {
	if x != nil && x.ContactMobile != nil {
		return *x.ContactMobile
	}
	return ""
}

func (x *TenantObject) GetExpireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireDate
	}
	return nil
}

func (x *TenantObject) GetAccountTotal() int64 {
	if x != nil && x.AccountTotal != nil {
		return *x.AccountTotal
	}
	return 0
}

func (x *TenantObject) GetPackageId() int64 {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return 0
}

func (x *TenantObject) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantObject) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *TenantObject) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *TenantObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TenantObject) GetUpdater() string {
	if x != nil && x.Updater != nil {
		return *x.Updater
	}
	return ""
}

func (x *TenantObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// TenantTotalResponse 列表数据总量
type TenantTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantTotalResponse) Reset() {
	*x = TenantTotalResponse{}
	mi := &file_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTotalResponse) ProtoMessage() {}

func (x *TenantTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTotalResponse.ProtoReflect.Descriptor instead.
func (*TenantTotalResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// TenantCreateRequest 创建数据请求
type TenantCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TenantObject          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCreateRequest) Reset() {
	*x = TenantCreateRequest{}
	mi := &file_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCreateRequest) ProtoMessage() {}

func (x *TenantCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCreateRequest.ProtoReflect.Descriptor instead.
func (*TenantCreateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantCreateRequest) GetData() *TenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantCreateResponse 创建数据响应
type TenantCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCreateResponse) Reset() {
	*x = TenantCreateResponse{}
	mi := &file_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCreateResponse) ProtoMessage() {}

func (x *TenantCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCreateResponse.ProtoReflect.Descriptor instead.
func (*TenantCreateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// TenantUpdateRequest 更新数据请求
type TenantUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *TenantObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUpdateRequest) Reset() {
	*x = TenantUpdateRequest{}
	mi := &file_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUpdateRequest) ProtoMessage() {}

func (x *TenantUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUpdateRequest.ProtoReflect.Descriptor instead.
func (*TenantUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *TenantUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantUpdateRequest) GetData() *TenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantUpdateResponse 更新数据响应
type TenantUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUpdateResponse) Reset() {
	*x = TenantUpdateResponse{}
	mi := &file_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUpdateResponse) ProtoMessage() {}

func (x *TenantUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUpdateResponse.ProtoReflect.Descriptor instead.
func (*TenantUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *TenantUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantDeleteRequest 删除数据请求
type TenantDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDeleteRequest) Reset() {
	*x = TenantDeleteRequest{}
	mi := &file_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDeleteRequest) ProtoMessage() {}

func (x *TenantDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDeleteRequest.ProtoReflect.Descriptor instead.
func (*TenantDeleteRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *TenantDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantDeleteResponse 删除数据响应
type TenantDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDeleteResponse) Reset() {
	*x = TenantDeleteResponse{}
	mi := &file_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDeleteResponse) ProtoMessage() {}

func (x *TenantDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDeleteResponse.ProtoReflect.Descriptor instead.
func (*TenantDeleteResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *TenantDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantRequest 查询单条数据请求
type TenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequest) Reset() {
	*x = TenantRequest{}
	mi := &file_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequest) ProtoMessage() {}

func (x *TenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequest.ProtoReflect.Descriptor instead.
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *TenantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantResponse 查询单条数据响应
type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *TenantObject          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *TenantResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantResponse) GetData() *TenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantRecoverRequest 恢复数据请求
type TenantRecoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRecoverRequest) Reset() {
	*x = TenantRecoverRequest{}
	mi := &file_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRecoverRequest) ProtoMessage() {}

func (x *TenantRecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRecoverRequest.ProtoReflect.Descriptor instead.
func (*TenantRecoverRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *TenantRecoverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantRecoverResponse 删除数据响应
type TenantRecoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRecoverResponse) Reset() {
	*x = TenantRecoverResponse{}
	mi := &file_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRecoverResponse) ProtoMessage() {}

func (x *TenantRecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRecoverResponse.ProtoReflect.Descriptor instead.
func (*TenantRecoverResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *TenantRecoverResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantRecoverResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantDropRequest 清理数据请求
type TenantDropRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDropRequest) Reset() {
	*x = TenantDropRequest{}
	mi := &file_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDropRequest) ProtoMessage() {}

func (x *TenantDropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDropRequest.ProtoReflect.Descriptor instead.
func (*TenantDropRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *TenantDropRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantDropResponse 清理数据响应
type TenantDropResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDropResponse) Reset() {
	*x = TenantDropResponse{}
	mi := &file_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDropResponse) ProtoMessage() {}

func (x *TenantDropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDropResponse.ProtoReflect.Descriptor instead.
func (*TenantDropResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *TenantDropResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantDropResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantListRequest 列表数据
type TenantListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"package_id" json:"packageId"
	PackageId *int64 `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3,oneof" json:"packageId" db:"package_id"` // 套餐编号
	// @inject_tag: db:"deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,2,opt,name=deleted,proto3,oneof" json:"deleted" db:"deleted"` // 删除:0否/1是
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	// @inject_tag: db:"expire_date" json:"expireDate"
	ExpireDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_date,json=expireDate,proto3" json:"expireDate" db:"expire_date"` // 过期时间
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,6,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantListRequest) Reset() {
	*x = TenantListRequest{}
	mi := &file_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListRequest) ProtoMessage() {}

func (x *TenantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantListRequest.ProtoReflect.Descriptor instead.
func (*TenantListRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *TenantListRequest) GetPackageId() int64 {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return 0
}

func (x *TenantListRequest) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *TenantListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TenantListRequest) GetExpireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireDate
	}
	return nil
}

func (x *TenantListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// TenantListResponse 数据响应
type TenantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*TenantObject        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantListResponse) Reset() {
	*x = TenantListResponse{}
	mi := &file_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListResponse) ProtoMessage() {}

func (x *TenantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantListResponse.ProtoReflect.Descriptor instead.
func (*TenantListResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *TenantListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantListResponse) GetData() []*TenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantListTotalRequest 列表数据
type TenantListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"package_id" json:"packageId"
	PackageId *int64 `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3,oneof" json:"packageId" db:"package_id"` // 套餐编号
	// @inject_tag: db:"deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,2,opt,name=deleted,proto3,oneof" json:"deleted" db:"deleted"` // 删除:0否/1是
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	// @inject_tag: db:"expire_date" json:"expireDate"
	ExpireDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_date,json=expireDate,proto3" json:"expireDate" db:"expire_date"` // 过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantListTotalRequest) Reset() {
	*x = TenantListTotalRequest{}
	mi := &file_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListTotalRequest) ProtoMessage() {}

func (x *TenantListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantListTotalRequest.ProtoReflect.Descriptor instead.
func (*TenantListTotalRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *TenantListTotalRequest) GetPackageId() int64 {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return 0
}

func (x *TenantListTotalRequest) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *TenantListTotalRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantListTotalRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TenantListTotalRequest) GetExpireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireDate
	}
	return nil
}

var File_tenant_proto protoreflect.FileDescriptor

const file_tenant_proto_rawDesc = "" +
	"\n" +
	"\ftenant.proto\x12\x06tenant\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"\xbd\x05\n" +
	"\fTenantObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\x03H\x02R\x06userId\x88\x01\x01\x12&\n" +
	"\fcontact_name\x18\x04 \x01(\tH\x03R\vcontactName\x88\x01\x01\x12*\n" +
	"\x0econtact_mobile\x18\x05 \x01(\tH\x04R\rcontactMobile\x88\x01\x01\x12;\n" +
	"\vexpire_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireDate\x12(\n" +
	"\raccount_total\x18\a \x01(\x03H\x05R\faccountTotal\x88\x01\x01\x12\"\n" +
	"\n" +
	"package_id\x18\b \x01(\x03H\x06R\tpackageId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\t \x01(\x05H\aR\x06status\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\n" +
	" \x01(\x05H\bR\adeleted\x88\x01\x01\x12\x1d\n" +
	"\acreator\x18\v \x01(\tH\tR\acreator\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1d\n" +
	"\aupdater\x18\r \x01(\tH\n" +
	"R\aupdater\x88\x01\x01\x12;\n" +
	"\vupdate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_user_idB\x0f\n" +
	"\r_contact_nameB\x11\n" +
	"\x0f_contact_mobileB\x10\n" +
	"\x0e_account_totalB\r\n" +
	"\v_package_idB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_deletedB\n" +
	"\n" +
	"\b_creatorB\n" +
	"\n" +
	"\b_updater\"O\n" +
	"\x13TenantTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"?\n" +
	"\x13TenantCreateRequest\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.tenant.TenantObjectR\x04data\"P\n" +
	"\x14TenantCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"O\n" +
	"\x13TenantUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.tenant.TenantObjectR\x04data\"<\n" +
	"\x14TenantUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"%\n" +
	"\x13TenantDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"<\n" +
	"\x14TenantDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1f\n" +
	"\rTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"`\n" +
	"\x0eTenantResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.tenant.TenantObjectR\x04data\"&\n" +
	"\x14TenantRecoverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x15TenantRecoverResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"#\n" +
	"\x11TenantDropRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x12TenantDropResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xcb\x02\n" +
	"\x11TenantListRequest\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\x03H\x00R\tpackageId\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\x02 \x01(\x05H\x01R\adeleted\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x02R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01\x12;\n" +
	"\vexpire_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireDate\x12B\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2\x1d.pagination.PaginationRequestH\x04R\n" +
	"pagination\x88\x01\x01B\r\n" +
	"\v_package_idB\n" +
	"\n" +
	"\b_deletedB\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\r\n" +
	"\v_pagination\"d\n" +
	"\x12TenantListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.tenant.TenantObjectR\x04data\"\xfd\x01\n" +
	"\x16TenantListTotalRequest\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\x03H\x00R\tpackageId\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\x02 \x01(\x05H\x01R\adeleted\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x02R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01\x12;\n" +
	"\vexpire_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireDateB\r\n" +
	"\v_package_idB\n" +
	"\n" +
	"\b_deletedB\t\n" +
	"\a_statusB\a\n" +
	"\x05_name2\xd1\x04\n" +
	"\rTenantService\x12I\n" +
	"\fTenantCreate\x12\x1b.tenant.TenantCreateRequest\x1a\x1c.tenant.TenantCreateResponse\x12I\n" +
	"\fTenantUpdate\x12\x1b.tenant.TenantUpdateRequest\x1a\x1c.tenant.TenantUpdateResponse\x12I\n" +
	"\fTenantDelete\x12\x1b.tenant.TenantDeleteRequest\x1a\x1c.tenant.TenantDeleteResponse\x127\n" +
	"\x06Tenant\x12\x15.tenant.TenantRequest\x1a\x16.tenant.TenantResponse\x12L\n" +
	"\rTenantRecover\x12\x1c.tenant.TenantRecoverRequest\x1a\x1d.tenant.TenantRecoverResponse\x12C\n" +
	"\n" +
	"TenantDrop\x12\x19.tenant.TenantDropRequest\x1a\x1a.tenant.TenantDropResponse\x12C\n" +
	"\n" +
	"TenantList\x12\x19.tenant.TenantListRequest\x1a\x1a.tenant.TenantListResponse\x12N\n" +
	"\x0fTenantListTotal\x12\x1e.tenant.TenantListTotalRequest\x1a\x1b.tenant.TenantTotalResponseB\x1dZ\x1bcloud/service/tenant;tenantb\x06proto3"

var (
	file_tenant_proto_rawDescOnce sync.Once
	file_tenant_proto_rawDescData []byte
)

func file_tenant_proto_rawDescGZIP() []byte {
	file_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)))
	})
	return file_tenant_proto_rawDescData
}

var file_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tenant_proto_goTypes = []any{
	(*TenantObject)(nil),                 // 0: tenant.TenantObject
	(*TenantTotalResponse)(nil),          // 1: tenant.TenantTotalResponse
	(*TenantCreateRequest)(nil),          // 2: tenant.TenantCreateRequest
	(*TenantCreateResponse)(nil),         // 3: tenant.TenantCreateResponse
	(*TenantUpdateRequest)(nil),          // 4: tenant.TenantUpdateRequest
	(*TenantUpdateResponse)(nil),         // 5: tenant.TenantUpdateResponse
	(*TenantDeleteRequest)(nil),          // 6: tenant.TenantDeleteRequest
	(*TenantDeleteResponse)(nil),         // 7: tenant.TenantDeleteResponse
	(*TenantRequest)(nil),                // 8: tenant.TenantRequest
	(*TenantResponse)(nil),               // 9: tenant.TenantResponse
	(*TenantRecoverRequest)(nil),         // 10: tenant.TenantRecoverRequest
	(*TenantRecoverResponse)(nil),        // 11: tenant.TenantRecoverResponse
	(*TenantDropRequest)(nil),            // 12: tenant.TenantDropRequest
	(*TenantDropResponse)(nil),           // 13: tenant.TenantDropResponse
	(*TenantListRequest)(nil),            // 14: tenant.TenantListRequest
	(*TenantListResponse)(nil),           // 15: tenant.TenantListResponse
	(*TenantListTotalRequest)(nil),       // 16: tenant.TenantListTotalRequest
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
	(*pagination.PaginationRequest)(nil), // 18: pagination.PaginationRequest
}
var file_tenant_proto_depIdxs = []int32{
	17, // 0: tenant.TenantObject.expire_date:type_name -> google.protobuf.Timestamp
	17, // 1: tenant.TenantObject.create_time:type_name -> google.protobuf.Timestamp
	17, // 2: tenant.TenantObject.update_time:type_name -> google.protobuf.Timestamp
	0,  // 3: tenant.TenantCreateRequest.data:type_name -> tenant.TenantObject
	0,  // 4: tenant.TenantUpdateRequest.data:type_name -> tenant.TenantObject
	0,  // 5: tenant.TenantResponse.data:type_name -> tenant.TenantObject
	17, // 6: tenant.TenantListRequest.expire_date:type_name -> google.protobuf.Timestamp
	18, // 7: tenant.TenantListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 8: tenant.TenantListResponse.data:type_name -> tenant.TenantObject
	17, // 9: tenant.TenantListTotalRequest.expire_date:type_name -> google.protobuf.Timestamp
	2,  // 10: tenant.TenantService.TenantCreate:input_type -> tenant.TenantCreateRequest
	4,  // 11: tenant.TenantService.TenantUpdate:input_type -> tenant.TenantUpdateRequest
	6,  // 12: tenant.TenantService.TenantDelete:input_type -> tenant.TenantDeleteRequest
	8,  // 13: tenant.TenantService.Tenant:input_type -> tenant.TenantRequest
	10, // 14: tenant.TenantService.TenantRecover:input_type -> tenant.TenantRecoverRequest
	12, // 15: tenant.TenantService.TenantDrop:input_type -> tenant.TenantDropRequest
	14, // 16: tenant.TenantService.TenantList:input_type -> tenant.TenantListRequest
	16, // 17: tenant.TenantService.TenantListTotal:input_type -> tenant.TenantListTotalRequest
	3,  // 18: tenant.TenantService.TenantCreate:output_type -> tenant.TenantCreateResponse
	5,  // 19: tenant.TenantService.TenantUpdate:output_type -> tenant.TenantUpdateResponse
	7,  // 20: tenant.TenantService.TenantDelete:output_type -> tenant.TenantDeleteResponse
	9,  // 21: tenant.TenantService.Tenant:output_type -> tenant.TenantResponse
	11, // 22: tenant.TenantService.TenantRecover:output_type -> tenant.TenantRecoverResponse
	13, // 23: tenant.TenantService.TenantDrop:output_type -> tenant.TenantDropResponse
	15, // 24: tenant.TenantService.TenantList:output_type -> tenant.TenantListResponse
	1,  // 25: tenant.TenantService.TenantListTotal:output_type -> tenant.TenantTotalResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tenant_proto_init() }
func file_tenant_proto_init() {
	if File_tenant_proto != nil {
		return
	}
	file_tenant_proto_msgTypes[0].OneofWrappers = []any{}
	file_tenant_proto_msgTypes[14].OneofWrappers = []any{}
	file_tenant_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_proto_depIdxs,
		MessageInfos:      file_tenant_proto_msgTypes,
	}.Build()
	File_tenant_proto = out.File
	file_tenant_proto_goTypes = nil
	file_tenant_proto_depIdxs = nil
}
