// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tenant_package.proto

// tenant_package 租户套餐

package tenant

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantPackageObject 数据对象
type TenantPackageObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:name" json:"name"
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name" gorm:"column:name"` //名称
	// @inject_tag: gorm:"column:scope_menu" json:"scopeMenu"
	ScopeMenu []byte `protobuf:"bytes,3,opt,name=scope_menu,json=scopeMenu,proto3,oneof" json:"scopeMenu" gorm:"column:scope_menu"` //数据范围
	// @inject_tag: gorm:"column:sort" json:"sort"
	Sort *int32 `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort" gorm:"column:sort"` //排序
	// @inject_tag: gorm:"column:status" json:"status"
	Status *int32 `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status" gorm:"column:status"` //状态:0正常/1停用
	// @inject_tag: gorm:"column:remark" json:"remark"
	Remark *string `protobuf:"bytes,6,opt,name=remark,proto3,oneof" json:"remark" gorm:"column:remark"` //备注
	// @inject_tag: gorm:"column:creator" json:"creator"
	Creator *string `protobuf:"bytes,7,opt,name=creator,proto3,oneof" json:"creator" gorm:"column:creator"` //创建人
	// @inject_tag: gorm:"column:create_time" json:"createTime"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"createTime" gorm:"column:create_time"` //创建时间
	// @inject_tag: gorm:"column:updater" json:"updater"
	Updater *string `protobuf:"bytes,9,opt,name=updater,proto3,oneof" json:"updater" gorm:"column:updater"` //更新人
	// @inject_tag: gorm:"column:update_time" json:"updateTime"
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"updateTime" gorm:"column:update_time"` //更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageObject) Reset() {
	*x = TenantPackageObject{}
	mi := &file_tenant_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageObject) ProtoMessage() {}

func (x *TenantPackageObject) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageObject.ProtoReflect.Descriptor instead.
func (*TenantPackageObject) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{0}
}

func (x *TenantPackageObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TenantPackageObject) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TenantPackageObject) GetScopeMenu() []byte {
	if x != nil {
		return x.ScopeMenu
	}
	return nil
}

func (x *TenantPackageObject) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *TenantPackageObject) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantPackageObject) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *TenantPackageObject) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *TenantPackageObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TenantPackageObject) GetUpdater() string {
	if x != nil && x.Updater != nil {
		return *x.Updater
	}
	return ""
}

func (x *TenantPackageObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// TenantPackageTotalResponse 列表数据总量
type TenantPackageTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageTotalResponse) Reset() {
	*x = TenantPackageTotalResponse{}
	mi := &file_tenant_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageTotalResponse) ProtoMessage() {}

func (x *TenantPackageTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageTotalResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageTotalResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{1}
}

func (x *TenantPackageTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantPackageTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// TenantPackageCreateRequest 创建数据请求
type TenantPackageCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TenantPackageObject   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageCreateRequest) Reset() {
	*x = TenantPackageCreateRequest{}
	mi := &file_tenant_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageCreateRequest) ProtoMessage() {}

func (x *TenantPackageCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageCreateRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageCreateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{2}
}

func (x *TenantPackageCreateRequest) GetData() *TenantPackageObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantPackageCreateResponse 创建数据响应
type TenantPackageCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageCreateResponse) Reset() {
	*x = TenantPackageCreateResponse{}
	mi := &file_tenant_package_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageCreateResponse) ProtoMessage() {}

func (x *TenantPackageCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageCreateResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageCreateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{3}
}

func (x *TenantPackageCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantPackageCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// TenantPackageUpdateRequest 更新数据请求
type TenantPackageUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *TenantPackageObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageUpdateRequest) Reset() {
	*x = TenantPackageUpdateRequest{}
	mi := &file_tenant_package_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageUpdateRequest) ProtoMessage() {}

func (x *TenantPackageUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageUpdateRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{4}
}

func (x *TenantPackageUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantPackageUpdateRequest) GetData() *TenantPackageObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantPackageUpdateResponse 更新数据响应
type TenantPackageUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageUpdateResponse) Reset() {
	*x = TenantPackageUpdateResponse{}
	mi := &file_tenant_package_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageUpdateResponse) ProtoMessage() {}

func (x *TenantPackageUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageUpdateResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{5}
}

func (x *TenantPackageUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantPackageDeleteRequest 删除数据请求
type TenantPackageDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageDeleteRequest) Reset() {
	*x = TenantPackageDeleteRequest{}
	mi := &file_tenant_package_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageDeleteRequest) ProtoMessage() {}

func (x *TenantPackageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageDeleteRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{6}
}

func (x *TenantPackageDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantPackageDeleteResponse 删除数据响应
type TenantPackageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageDeleteResponse) Reset() {
	*x = TenantPackageDeleteResponse{}
	mi := &file_tenant_package_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageDeleteResponse) ProtoMessage() {}

func (x *TenantPackageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageDeleteResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{7}
}

func (x *TenantPackageDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// TenantPackageRequest 查询单条数据请求
type TenantPackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageRequest) Reset() {
	*x = TenantPackageRequest{}
	mi := &file_tenant_package_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageRequest) ProtoMessage() {}

func (x *TenantPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{8}
}

func (x *TenantPackageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// TenantPackageResponse 查询单条数据响应
type TenantPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *TenantPackageObject   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageResponse) Reset() {
	*x = TenantPackageResponse{}
	mi := &file_tenant_package_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageResponse) ProtoMessage() {}

func (x *TenantPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{9}
}

func (x *TenantPackageResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantPackageResponse) GetData() *TenantPackageObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantPackageListRequest 列表数据
type TenantPackageListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageListRequest) Reset() {
	*x = TenantPackageListRequest{}
	mi := &file_tenant_package_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageListRequest) ProtoMessage() {}

func (x *TenantPackageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageListRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageListRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{10}
}

func (x *TenantPackageListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantPackageListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TenantPackageListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// TenantPackageListResponse 数据响应
type TenantPackageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*TenantPackageObject `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageListResponse) Reset() {
	*x = TenantPackageListResponse{}
	mi := &file_tenant_package_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageListResponse) ProtoMessage() {}

func (x *TenantPackageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageListResponse.ProtoReflect.Descriptor instead.
func (*TenantPackageListResponse) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{11}
}

func (x *TenantPackageListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TenantPackageListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TenantPackageListResponse) GetData() []*TenantPackageObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// TenantPackageListTotalRequest 列表数据
type TenantPackageListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name          *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantPackageListTotalRequest) Reset() {
	*x = TenantPackageListTotalRequest{}
	mi := &file_tenant_package_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPackageListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPackageListTotalRequest) ProtoMessage() {}

func (x *TenantPackageListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_package_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantPackageListTotalRequest.ProtoReflect.Descriptor instead.
func (*TenantPackageListTotalRequest) Descriptor() ([]byte, []int) {
	return file_tenant_package_proto_rawDescGZIP(), []int{12}
}

func (x *TenantPackageListTotalRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TenantPackageListTotalRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_tenant_package_proto protoreflect.FileDescriptor

const file_tenant_package_proto_rawDesc = "" +
	"\n" +
	"\x14tenant_package.proto\x12\x06tenant\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"\xc8\x03\n" +
	"\x13TenantPackageObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"scope_menu\x18\x03 \x01(\fH\x02R\tscopeMenu\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\x05H\x03R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\x05H\x04R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\x06 \x01(\tH\x05R\x06remark\x88\x01\x01\x12\x1d\n" +
	"\acreator\x18\a \x01(\tH\x06R\acreator\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1d\n" +
	"\aupdater\x18\t \x01(\tH\aR\aupdater\x88\x01\x01\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\r\n" +
	"\v_scope_menuB\a\n" +
	"\x05_sortB\t\n" +
	"\a_statusB\t\n" +
	"\a_remarkB\n" +
	"\n" +
	"\b_creatorB\n" +
	"\n" +
	"\b_updater\"V\n" +
	"\x1aTenantPackageTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"M\n" +
	"\x1aTenantPackageCreateRequest\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.tenant.TenantPackageObjectR\x04data\"W\n" +
	"\x1bTenantPackageCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"]\n" +
	"\x1aTenantPackageUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x1b.tenant.TenantPackageObjectR\x04data\"C\n" +
	"\x1bTenantPackageUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\",\n" +
	"\x1aTenantPackageDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x1bTenantPackageDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"&\n" +
	"\x14TenantPackageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"n\n" +
	"\x15TenantPackageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.tenant.TenantPackageObjectR\x04data\"\xb7\x01\n" +
	"\x18TenantPackageListRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.pagination.PaginationRequestH\x02R\n" +
	"pagination\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\r\n" +
	"\v_pagination\"r\n" +
	"\x19TenantPackageListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.tenant.TenantPackageObjectR\x04data\"i\n" +
	"\x1dTenantPackageListTotalRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_name2\xc3\x04\n" +
	"\x14TenantPackageService\x12^\n" +
	"\x13TenantPackageCreate\x12\".tenant.TenantPackageCreateRequest\x1a#.tenant.TenantPackageCreateResponse\x12^\n" +
	"\x13TenantPackageUpdate\x12\".tenant.TenantPackageUpdateRequest\x1a#.tenant.TenantPackageUpdateResponse\x12^\n" +
	"\x13TenantPackageDelete\x12\".tenant.TenantPackageDeleteRequest\x1a#.tenant.TenantPackageDeleteResponse\x12L\n" +
	"\rTenantPackage\x12\x1c.tenant.TenantPackageRequest\x1a\x1d.tenant.TenantPackageResponse\x12X\n" +
	"\x11TenantPackageList\x12 .tenant.TenantPackageListRequest\x1a!.tenant.TenantPackageListResponse\x12c\n" +
	"\x16TenantPackageListTotal\x12%.tenant.TenantPackageListTotalRequest\x1a\".tenant.TenantPackageTotalResponseB\x1dZ\x1bcloud/service/tenant;tenantb\x06proto3"

var (
	file_tenant_package_proto_rawDescOnce sync.Once
	file_tenant_package_proto_rawDescData []byte
)

func file_tenant_package_proto_rawDescGZIP() []byte {
	file_tenant_package_proto_rawDescOnce.Do(func() {
		file_tenant_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_package_proto_rawDesc), len(file_tenant_package_proto_rawDesc)))
	})
	return file_tenant_package_proto_rawDescData
}

var file_tenant_package_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tenant_package_proto_goTypes = []any{
	(*TenantPackageObject)(nil),           // 0: tenant.TenantPackageObject
	(*TenantPackageTotalResponse)(nil),    // 1: tenant.TenantPackageTotalResponse
	(*TenantPackageCreateRequest)(nil),    // 2: tenant.TenantPackageCreateRequest
	(*TenantPackageCreateResponse)(nil),   // 3: tenant.TenantPackageCreateResponse
	(*TenantPackageUpdateRequest)(nil),    // 4: tenant.TenantPackageUpdateRequest
	(*TenantPackageUpdateResponse)(nil),   // 5: tenant.TenantPackageUpdateResponse
	(*TenantPackageDeleteRequest)(nil),    // 6: tenant.TenantPackageDeleteRequest
	(*TenantPackageDeleteResponse)(nil),   // 7: tenant.TenantPackageDeleteResponse
	(*TenantPackageRequest)(nil),          // 8: tenant.TenantPackageRequest
	(*TenantPackageResponse)(nil),         // 9: tenant.TenantPackageResponse
	(*TenantPackageListRequest)(nil),      // 10: tenant.TenantPackageListRequest
	(*TenantPackageListResponse)(nil),     // 11: tenant.TenantPackageListResponse
	(*TenantPackageListTotalRequest)(nil), // 12: tenant.TenantPackageListTotalRequest
	(*timestamppb.Timestamp)(nil),         // 13: google.protobuf.Timestamp
	(*pagination.PaginationRequest)(nil),  // 14: pagination.PaginationRequest
}
var file_tenant_package_proto_depIdxs = []int32{
	13, // 0: tenant.TenantPackageObject.create_time:type_name -> google.protobuf.Timestamp
	13, // 1: tenant.TenantPackageObject.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: tenant.TenantPackageCreateRequest.data:type_name -> tenant.TenantPackageObject
	0,  // 3: tenant.TenantPackageUpdateRequest.data:type_name -> tenant.TenantPackageObject
	0,  // 4: tenant.TenantPackageResponse.data:type_name -> tenant.TenantPackageObject
	14, // 5: tenant.TenantPackageListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 6: tenant.TenantPackageListResponse.data:type_name -> tenant.TenantPackageObject
	2,  // 7: tenant.TenantPackageService.TenantPackageCreate:input_type -> tenant.TenantPackageCreateRequest
	4,  // 8: tenant.TenantPackageService.TenantPackageUpdate:input_type -> tenant.TenantPackageUpdateRequest
	6,  // 9: tenant.TenantPackageService.TenantPackageDelete:input_type -> tenant.TenantPackageDeleteRequest
	8,  // 10: tenant.TenantPackageService.TenantPackage:input_type -> tenant.TenantPackageRequest
	10, // 11: tenant.TenantPackageService.TenantPackageList:input_type -> tenant.TenantPackageListRequest
	12, // 12: tenant.TenantPackageService.TenantPackageListTotal:input_type -> tenant.TenantPackageListTotalRequest
	3,  // 13: tenant.TenantPackageService.TenantPackageCreate:output_type -> tenant.TenantPackageCreateResponse
	5,  // 14: tenant.TenantPackageService.TenantPackageUpdate:output_type -> tenant.TenantPackageUpdateResponse
	7,  // 15: tenant.TenantPackageService.TenantPackageDelete:output_type -> tenant.TenantPackageDeleteResponse
	9,  // 16: tenant.TenantPackageService.TenantPackage:output_type -> tenant.TenantPackageResponse
	11, // 17: tenant.TenantPackageService.TenantPackageList:output_type -> tenant.TenantPackageListResponse
	1,  // 18: tenant.TenantPackageService.TenantPackageListTotal:output_type -> tenant.TenantPackageTotalResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tenant_package_proto_init() }
func file_tenant_package_proto_init() {
	if File_tenant_package_proto != nil {
		return
	}
	file_tenant_package_proto_msgTypes[0].OneofWrappers = []any{}
	file_tenant_package_proto_msgTypes[10].OneofWrappers = []any{}
	file_tenant_package_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_package_proto_rawDesc), len(file_tenant_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_package_proto_goTypes,
		DependencyIndexes: file_tenant_package_proto_depIdxs,
		MessageInfos:      file_tenant_package_proto_msgTypes,
	}.Build()
	File_tenant_package_proto = out.File
	file_tenant_package_proto_goTypes = nil
	file_tenant_package_proto_depIdxs = nil
}
