# .github/stale.yml
# 规则：超过30天未活动、无question标签、无project/milestone的issue加stale标签
# 有question标签的issue，15天未活动加stale
# 有stale标签的issue，30天后关闭并锁定

daysUntilStale: 30
daysUntilClose: 30
staleLabel: stale
exemptLabels:
  - question
exemptProjects: true
exemptMilestones: true
only: issues

# 自定义规则
issues:
  # 默认规则：30天未活动、无question标签、无project/milestone，加stale
  staleLabel: stale
  daysUntilStale: 30
  daysUntilClose: 30
  exemptLabels:
    - question
  exemptProjects: true
  exemptMilestones: true
  markComment: >
    此 issue 已超过 30 天未活动，已被标记为 stale。如果没有进一步的活动，将在 30 天后自动关闭。
  closeComment: >
    此 issue 已被关闭并锁定，如需讨论请新开 issue。

  # 针对 question 标签的特殊规则
  labels:
    question:
      daysUntilStale: 15
      daysUntilClose: 30
      staleLabel: stale
      markComment: >
        此 question 类型 issue 已 15 天未活动，已被标记为 stale。如果没有进一步的活动，将在 30 天后自动关闭。
      closeComment: >
        此 issue 已被关闭并锁定，如需讨论请新开 issue。

lockClosed: true
