// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: sys_dict_type.proto

// sys_dict_type 字典类型

package dict

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysDictTypeService_SysDictTypeCreate_FullMethodName    = "/dict.SysDictTypeService/SysDictTypeCreate"
	SysDictTypeService_SysDictTypeUpdate_FullMethodName    = "/dict.SysDictTypeService/SysDictTypeUpdate"
	SysDictTypeService_SysDictTypeDelete_FullMethodName    = "/dict.SysDictTypeService/SysDictTypeDelete"
	SysDictTypeService_SysDictType_FullMethodName          = "/dict.SysDictTypeService/SysDictType"
	SysDictTypeService_SysDictTypeType_FullMethodName      = "/dict.SysDictTypeService/SysDictTypeType"
	SysDictTypeService_SysDictTypeList_FullMethodName      = "/dict.SysDictTypeService/SysDictTypeList"
	SysDictTypeService_SysDictTypeListTotal_FullMethodName = "/dict.SysDictTypeService/SysDictTypeListTotal"
)

// SysDictTypeServiceClient is the client API for SysDictTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysDictTypeService 服务
type SysDictTypeServiceClient interface {
	SysDictTypeCreate(ctx context.Context, in *SysDictTypeCreateRequest, opts ...grpc.CallOption) (*SysDictTypeCreateResponse, error)
	SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateRequest, opts ...grpc.CallOption) (*SysDictTypeUpdateResponse, error)
	SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteRequest, opts ...grpc.CallOption) (*SysDictTypeDeleteResponse, error)
	SysDictType(ctx context.Context, in *SysDictTypeRequest, opts ...grpc.CallOption) (*SysDictTypeResponse, error)
	SysDictTypeType(ctx context.Context, in *SysDictTypeTypeRequest, opts ...grpc.CallOption) (*SysDictTypeTypeResponse, error)
	SysDictTypeList(ctx context.Context, in *SysDictTypeListRequest, opts ...grpc.CallOption) (*SysDictTypeListResponse, error)
	SysDictTypeListTotal(ctx context.Context, in *SysDictTypeListTotalRequest, opts ...grpc.CallOption) (*SysDictTypeTotalResponse, error)
}

type sysDictTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysDictTypeServiceClient(cc grpc.ClientConnInterface) SysDictTypeServiceClient {
	return &sysDictTypeServiceClient{cc}
}

func (c *sysDictTypeServiceClient) SysDictTypeCreate(ctx context.Context, in *SysDictTypeCreateRequest, opts ...grpc.CallOption) (*SysDictTypeCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeCreateResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictTypeUpdate(ctx context.Context, in *SysDictTypeUpdateRequest, opts ...grpc.CallOption) (*SysDictTypeUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeUpdateResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictTypeDelete(ctx context.Context, in *SysDictTypeDeleteRequest, opts ...grpc.CallOption) (*SysDictTypeDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeDeleteResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictType(ctx context.Context, in *SysDictTypeRequest, opts ...grpc.CallOption) (*SysDictTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictTypeType(ctx context.Context, in *SysDictTypeTypeRequest, opts ...grpc.CallOption) (*SysDictTypeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeTypeResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictTypeList(ctx context.Context, in *SysDictTypeListRequest, opts ...grpc.CallOption) (*SysDictTypeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeListResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysDictTypeServiceClient) SysDictTypeListTotal(ctx context.Context, in *SysDictTypeListTotalRequest, opts ...grpc.CallOption) (*SysDictTypeTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysDictTypeTotalResponse)
	err := c.cc.Invoke(ctx, SysDictTypeService_SysDictTypeListTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysDictTypeServiceServer is the server API for SysDictTypeService service.
// All implementations must embed UnimplementedSysDictTypeServiceServer
// for forward compatibility.
//
// SysDictTypeService 服务
type SysDictTypeServiceServer interface {
	SysDictTypeCreate(context.Context, *SysDictTypeCreateRequest) (*SysDictTypeCreateResponse, error)
	SysDictTypeUpdate(context.Context, *SysDictTypeUpdateRequest) (*SysDictTypeUpdateResponse, error)
	SysDictTypeDelete(context.Context, *SysDictTypeDeleteRequest) (*SysDictTypeDeleteResponse, error)
	SysDictType(context.Context, *SysDictTypeRequest) (*SysDictTypeResponse, error)
	SysDictTypeType(context.Context, *SysDictTypeTypeRequest) (*SysDictTypeTypeResponse, error)
	SysDictTypeList(context.Context, *SysDictTypeListRequest) (*SysDictTypeListResponse, error)
	SysDictTypeListTotal(context.Context, *SysDictTypeListTotalRequest) (*SysDictTypeTotalResponse, error)
	mustEmbedUnimplementedSysDictTypeServiceServer()
}

// UnimplementedSysDictTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysDictTypeServiceServer struct{}

func (UnimplementedSysDictTypeServiceServer) SysDictTypeCreate(context.Context, *SysDictTypeCreateRequest) (*SysDictTypeCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeCreate not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictTypeUpdate(context.Context, *SysDictTypeUpdateRequest) (*SysDictTypeUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeUpdate not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictTypeDelete(context.Context, *SysDictTypeDeleteRequest) (*SysDictTypeDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeDelete not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictType(context.Context, *SysDictTypeRequest) (*SysDictTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictType not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictTypeType(context.Context, *SysDictTypeTypeRequest) (*SysDictTypeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeType not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictTypeList(context.Context, *SysDictTypeListRequest) (*SysDictTypeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeList not implemented")
}
func (UnimplementedSysDictTypeServiceServer) SysDictTypeListTotal(context.Context, *SysDictTypeListTotalRequest) (*SysDictTypeTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysDictTypeListTotal not implemented")
}
func (UnimplementedSysDictTypeServiceServer) mustEmbedUnimplementedSysDictTypeServiceServer() {}
func (UnimplementedSysDictTypeServiceServer) testEmbeddedByValue()                            {}

// UnsafeSysDictTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysDictTypeServiceServer will
// result in compilation errors.
type UnsafeSysDictTypeServiceServer interface {
	mustEmbedUnimplementedSysDictTypeServiceServer()
}

func RegisterSysDictTypeServiceServer(s grpc.ServiceRegistrar, srv SysDictTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSysDictTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysDictTypeService_ServiceDesc, srv)
}

func _SysDictTypeService_SysDictTypeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeCreate(ctx, req.(*SysDictTypeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictTypeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeUpdate(ctx, req.(*SysDictTypeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictTypeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeDelete(ctx, req.(*SysDictTypeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictType(ctx, req.(*SysDictTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictTypeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeType(ctx, req.(*SysDictTypeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictTypeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeList(ctx, req.(*SysDictTypeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysDictTypeService_SysDictTypeListTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysDictTypeListTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysDictTypeServiceServer).SysDictTypeListTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysDictTypeService_SysDictTypeListTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysDictTypeServiceServer).SysDictTypeListTotal(ctx, req.(*SysDictTypeListTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysDictTypeService_ServiceDesc is the grpc.ServiceDesc for SysDictTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysDictTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dict.SysDictTypeService",
	HandlerType: (*SysDictTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysDictTypeCreate",
			Handler:    _SysDictTypeService_SysDictTypeCreate_Handler,
		},
		{
			MethodName: "SysDictTypeUpdate",
			Handler:    _SysDictTypeService_SysDictTypeUpdate_Handler,
		},
		{
			MethodName: "SysDictTypeDelete",
			Handler:    _SysDictTypeService_SysDictTypeDelete_Handler,
		},
		{
			MethodName: "SysDictType",
			Handler:    _SysDictTypeService_SysDictType_Handler,
		},
		{
			MethodName: "SysDictTypeType",
			Handler:    _SysDictTypeService_SysDictTypeType_Handler,
		},
		{
			MethodName: "SysDictTypeList",
			Handler:    _SysDictTypeService_SysDictTypeList_Handler,
		},
		{
			MethodName: "SysDictTypeListTotal",
			Handler:    _SysDictTypeService_SysDictTypeListTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_dict_type.proto",
}
