// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: sys_role.proto

// sys_role 角色

package role

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SysRoleObject 数据对象
type SysRoleObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:name" json:"name"
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name" gorm:"column:name"` //名称
	// @inject_tag: gorm:"column:code" json:"code"
	Code *string `protobuf:"bytes,3,opt,name=code,proto3,oneof" json:"code" gorm:"column:code"` //编码
	// @inject_tag: gorm:"column:data_scope" json:"dataScope"
	DataScope *int32 `protobuf:"varint,4,opt,name=data_scope,json=dataScope,proto3,oneof" json:"dataScope" gorm:"column:data_scope"` //数据范围:1:全部数据权限/2:自定数据权限/3:本部门数据权限/4:本部门及以下数据权限
	// @inject_tag: gorm:"column:data_scope_dept" json:"dataScopeDept"
	DataScopeDept []byte `protobuf:"bytes,5,opt,name=data_scope_dept,json=dataScopeDept,proto3,oneof" json:"dataScopeDept" gorm:"column:data_scope_dept"` //数据范围(指定部门数组)
	// @inject_tag: gorm:"column:sort" json:"sort"
	Sort *int32 `protobuf:"varint,6,opt,name=sort,proto3,oneof" json:"sort" gorm:"column:sort"` //排序
	// @inject_tag: gorm:"column:status" json:"status"
	Status *int32 `protobuf:"varint,7,opt,name=status,proto3,oneof" json:"status" gorm:"column:status"` //状态:0正常/1停用
	// @inject_tag: gorm:"column:deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,8,opt,name=deleted,proto3,oneof" json:"deleted" gorm:"column:deleted"` //删除:0否/1是
	// @inject_tag: gorm:"column:tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,9,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" gorm:"column:tenant_id"` //租户
	// @inject_tag: gorm:"column:creator" json:"creator"
	Creator *string `protobuf:"bytes,10,opt,name=creator,proto3,oneof" json:"creator" gorm:"column:creator"` //创建人
	// @inject_tag: gorm:"column:create_time" json:"createTime"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"createTime" gorm:"column:create_time"` //创建时间
	// @inject_tag: gorm:"column:updater" json:"updater"
	Updater *string `protobuf:"bytes,12,opt,name=updater,proto3,oneof" json:"updater" gorm:"column:updater"` //更新人
	// @inject_tag: gorm:"column:update_time" json:"updateTime"
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"updateTime" gorm:"column:update_time"` //更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleObject) Reset() {
	*x = SysRoleObject{}
	mi := &file_sys_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleObject) ProtoMessage() {}

func (x *SysRoleObject) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleObject.ProtoReflect.Descriptor instead.
func (*SysRoleObject) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{0}
}

func (x *SysRoleObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SysRoleObject) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SysRoleObject) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *SysRoleObject) GetDataScope() int32 {
	if x != nil && x.DataScope != nil {
		return *x.DataScope
	}
	return 0
}

func (x *SysRoleObject) GetDataScopeDept() []byte {
	if x != nil {
		return x.DataScopeDept
	}
	return nil
}

func (x *SysRoleObject) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *SysRoleObject) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SysRoleObject) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *SysRoleObject) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysRoleObject) GetCreator() string {
	if x != nil && x.Creator != nil {
		return *x.Creator
	}
	return ""
}

func (x *SysRoleObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SysRoleObject) GetUpdater() string {
	if x != nil && x.Updater != nil {
		return *x.Updater
	}
	return ""
}

func (x *SysRoleObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// SysRoleTotalResponse 列表数据总量
type SysRoleTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleTotalResponse) Reset() {
	*x = SysRoleTotalResponse{}
	mi := &file_sys_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleTotalResponse) ProtoMessage() {}

func (x *SysRoleTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleTotalResponse.ProtoReflect.Descriptor instead.
func (*SysRoleTotalResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{1}
}

func (x *SysRoleTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysRoleTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysRoleCreateRequest 创建数据请求
type SysRoleCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SysRoleObject         `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleCreateRequest) Reset() {
	*x = SysRoleCreateRequest{}
	mi := &file_sys_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleCreateRequest) ProtoMessage() {}

func (x *SysRoleCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleCreateRequest.ProtoReflect.Descriptor instead.
func (*SysRoleCreateRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{2}
}

func (x *SysRoleCreateRequest) GetData() *SysRoleObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysRoleCreateResponse 创建数据响应
type SysRoleCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleCreateResponse) Reset() {
	*x = SysRoleCreateResponse{}
	mi := &file_sys_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleCreateResponse) ProtoMessage() {}

func (x *SysRoleCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleCreateResponse.ProtoReflect.Descriptor instead.
func (*SysRoleCreateResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{3}
}

func (x *SysRoleCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysRoleCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysRoleUpdateRequest 更新数据请求
type SysRoleUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *SysRoleObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleUpdateRequest) Reset() {
	*x = SysRoleUpdateRequest{}
	mi := &file_sys_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleUpdateRequest) ProtoMessage() {}

func (x *SysRoleUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleUpdateRequest.ProtoReflect.Descriptor instead.
func (*SysRoleUpdateRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{4}
}

func (x *SysRoleUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysRoleUpdateRequest) GetData() *SysRoleObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysRoleUpdateResponse 更新数据响应
type SysRoleUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleUpdateResponse) Reset() {
	*x = SysRoleUpdateResponse{}
	mi := &file_sys_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleUpdateResponse) ProtoMessage() {}

func (x *SysRoleUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleUpdateResponse.ProtoReflect.Descriptor instead.
func (*SysRoleUpdateResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{5}
}

func (x *SysRoleUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysRoleDeleteRequest 删除数据请求
type SysRoleDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleDeleteRequest) Reset() {
	*x = SysRoleDeleteRequest{}
	mi := &file_sys_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleDeleteRequest) ProtoMessage() {}

func (x *SysRoleDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleDeleteRequest.ProtoReflect.Descriptor instead.
func (*SysRoleDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{6}
}

func (x *SysRoleDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysRoleDeleteResponse 删除数据响应
type SysRoleDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleDeleteResponse) Reset() {
	*x = SysRoleDeleteResponse{}
	mi := &file_sys_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleDeleteResponse) ProtoMessage() {}

func (x *SysRoleDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleDeleteResponse.ProtoReflect.Descriptor instead.
func (*SysRoleDeleteResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{7}
}

func (x *SysRoleDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysRoleRequest 查询单条数据请求
type SysRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleRequest) Reset() {
	*x = SysRoleRequest{}
	mi := &file_sys_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleRequest) ProtoMessage() {}

func (x *SysRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleRequest.ProtoReflect.Descriptor instead.
func (*SysRoleRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{8}
}

func (x *SysRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysRoleResponse 查询单条数据响应
type SysRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysRoleObject         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleResponse) Reset() {
	*x = SysRoleResponse{}
	mi := &file_sys_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleResponse) ProtoMessage() {}

func (x *SysRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleResponse.ProtoReflect.Descriptor instead.
func (*SysRoleResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{9}
}

func (x *SysRoleResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysRoleResponse) GetData() *SysRoleObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysRoleRecoverRequest 恢复数据请求
type SysRoleRecoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleRecoverRequest) Reset() {
	*x = SysRoleRecoverRequest{}
	mi := &file_sys_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleRecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleRecoverRequest) ProtoMessage() {}

func (x *SysRoleRecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleRecoverRequest.ProtoReflect.Descriptor instead.
func (*SysRoleRecoverRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{10}
}

func (x *SysRoleRecoverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysRoleRecoverResponse 删除数据响应
type SysRoleRecoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleRecoverResponse) Reset() {
	*x = SysRoleRecoverResponse{}
	mi := &file_sys_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleRecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleRecoverResponse) ProtoMessage() {}

func (x *SysRoleRecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleRecoverResponse.ProtoReflect.Descriptor instead.
func (*SysRoleRecoverResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{11}
}

func (x *SysRoleRecoverResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleRecoverResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysRoleDropRequest 清理数据请求
type SysRoleDropRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleDropRequest) Reset() {
	*x = SysRoleDropRequest{}
	mi := &file_sys_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleDropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleDropRequest) ProtoMessage() {}

func (x *SysRoleDropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleDropRequest.ProtoReflect.Descriptor instead.
func (*SysRoleDropRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{12}
}

func (x *SysRoleDropRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysRoleDropResponse 清理数据响应
type SysRoleDropResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleDropResponse) Reset() {
	*x = SysRoleDropResponse{}
	mi := &file_sys_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleDropResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleDropResponse) ProtoMessage() {}

func (x *SysRoleDropResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleDropResponse.ProtoReflect.Descriptor instead.
func (*SysRoleDropResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{13}
}

func (x *SysRoleDropResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleDropResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysRoleCodeRequest 查询单条数据请求
type SysRoleCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"code" json:"code"
	Code          *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code" db:"code"` // 编码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleCodeRequest) Reset() {
	*x = SysRoleCodeRequest{}
	mi := &file_sys_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleCodeRequest) ProtoMessage() {}

func (x *SysRoleCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleCodeRequest.ProtoReflect.Descriptor instead.
func (*SysRoleCodeRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{14}
}

func (x *SysRoleCodeRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysRoleCodeRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

// SysRoleCodeResponse 查询单条数据响应
type SysRoleCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysRoleObject         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleCodeResponse) Reset() {
	*x = SysRoleCodeResponse{}
	mi := &file_sys_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleCodeResponse) ProtoMessage() {}

func (x *SysRoleCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleCodeResponse.ProtoReflect.Descriptor instead.
func (*SysRoleCodeResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{15}
}

func (x *SysRoleCodeResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysRoleCodeResponse) GetData() *SysRoleObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysRoleListRequest 列表数据
type SysRoleListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"code" json:"code"
	Code *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code" db:"code"` // 编码
	// @inject_tag: db:"deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,3,opt,name=deleted,proto3,oneof" json:"deleted" db:"deleted"` // 删除:0否/1是
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name *string `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,6,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleListRequest) Reset() {
	*x = SysRoleListRequest{}
	mi := &file_sys_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleListRequest) ProtoMessage() {}

func (x *SysRoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleListRequest.ProtoReflect.Descriptor instead.
func (*SysRoleListRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{16}
}

func (x *SysRoleListRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysRoleListRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *SysRoleListRequest) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *SysRoleListRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SysRoleListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SysRoleListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SysRoleListResponse 数据响应
type SysRoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*SysRoleObject       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleListResponse) Reset() {
	*x = SysRoleListResponse{}
	mi := &file_sys_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleListResponse) ProtoMessage() {}

func (x *SysRoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleListResponse.ProtoReflect.Descriptor instead.
func (*SysRoleListResponse) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{17}
}

func (x *SysRoleListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysRoleListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysRoleListResponse) GetData() []*SysRoleObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysRoleListTotalRequest 列表数据
type SysRoleListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"code" json:"code"
	Code *string `protobuf:"bytes,2,opt,name=code,proto3,oneof" json:"code" db:"code"` // 编码
	// @inject_tag: db:"deleted" json:"deleted"
	Deleted *int32 `protobuf:"varint,3,opt,name=deleted,proto3,oneof" json:"deleted" db:"deleted"` // 删除:0否/1是
	// @inject_tag: db:"status" json:"status"
	Status *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status" db:"status"` // 状态:0正常/1停用
	// @inject_tag: db:"name" json:"name"
	Name          *string `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name" db:"name"` // 名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysRoleListTotalRequest) Reset() {
	*x = SysRoleListTotalRequest{}
	mi := &file_sys_role_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysRoleListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysRoleListTotalRequest) ProtoMessage() {}

func (x *SysRoleListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_role_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysRoleListTotalRequest.ProtoReflect.Descriptor instead.
func (*SysRoleListTotalRequest) Descriptor() ([]byte, []int) {
	return file_sys_role_proto_rawDescGZIP(), []int{18}
}

func (x *SysRoleListTotalRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysRoleListTotalRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *SysRoleListTotalRequest) GetDeleted() int32 {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return 0
}

func (x *SysRoleListTotalRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SysRoleListTotalRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_sys_role_proto protoreflect.FileDescriptor

const file_sys_role_proto_rawDesc = "" +
	"\n" +
	"\x0esys_role.proto\x12\x04role\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"\xd8\x04\n" +
	"\rSysRoleObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\tH\x02R\x04code\x88\x01\x01\x12\"\n" +
	"\n" +
	"data_scope\x18\x04 \x01(\x05H\x03R\tdataScope\x88\x01\x01\x12+\n" +
	"\x0fdata_scope_dept\x18\x05 \x01(\fH\x04R\rdataScopeDept\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x06 \x01(\x05H\x05R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\x05H\x06R\x06status\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\b \x01(\x05H\aR\adeleted\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\t \x01(\x03H\bR\btenantId\x88\x01\x01\x12\x1d\n" +
	"\acreator\x18\n" +
	" \x01(\tH\tR\acreator\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x1d\n" +
	"\aupdater\x18\f \x01(\tH\n" +
	"R\aupdater\x88\x01\x01\x12;\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_codeB\r\n" +
	"\v_data_scopeB\x12\n" +
	"\x10_data_scope_deptB\a\n" +
	"\x05_sortB\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_deletedB\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_creatorB\n" +
	"\n" +
	"\b_updater\"P\n" +
	"\x14SysRoleTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"?\n" +
	"\x14SysRoleCreateRequest\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.role.SysRoleObjectR\x04data\"Q\n" +
	"\x15SysRoleCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"O\n" +
	"\x14SysRoleUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.role.SysRoleObjectR\x04data\"=\n" +
	"\x15SysRoleUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"&\n" +
	"\x14SysRoleDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x15SysRoleDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\" \n" +
	"\x0eSysRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"`\n" +
	"\x0fSysRoleResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.role.SysRoleObjectR\x04data\"'\n" +
	"\x15SysRoleRecoverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x16SysRoleRecoverResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"$\n" +
	"\x12SysRoleDropRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x13SysRoleDropResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"f\n" +
	"\x12SysRoleCodeRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x01R\x04code\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\a\n" +
	"\x05_code\"d\n" +
	"\x13SysRoleCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.role.SysRoleObjectR\x04data\"\xae\x02\n" +
	"\x12SysRoleListRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x01R\x04code\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\x03 \x01(\x05H\x02R\adeleted\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x03R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x04R\x04name\x88\x01\x01\x12B\n" +
	"\n" +
	"pagination\x18\x06 \x01(\v2\x1d.pagination.PaginationRequestH\x05R\n" +
	"pagination\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_deletedB\t\n" +
	"\a_statusB\a\n" +
	"\x05_nameB\r\n" +
	"\v_pagination\"d\n" +
	"\x13SysRoleListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.role.SysRoleObjectR\x04data\"\xe0\x01\n" +
	"\x17SysRoleListTotalRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tH\x01R\x04code\x88\x01\x01\x12\x1d\n" +
	"\adeleted\x18\x03 \x01(\x05H\x02R\adeleted\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x03R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x04R\x04name\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_deletedB\t\n" +
	"\a_statusB\a\n" +
	"\x05_name2\x8e\x05\n" +
	"\x0eSysRoleService\x12H\n" +
	"\rSysRoleCreate\x12\x1a.role.SysRoleCreateRequest\x1a\x1b.role.SysRoleCreateResponse\x12H\n" +
	"\rSysRoleUpdate\x12\x1a.role.SysRoleUpdateRequest\x1a\x1b.role.SysRoleUpdateResponse\x12H\n" +
	"\rSysRoleDelete\x12\x1a.role.SysRoleDeleteRequest\x1a\x1b.role.SysRoleDeleteResponse\x126\n" +
	"\aSysRole\x12\x14.role.SysRoleRequest\x1a\x15.role.SysRoleResponse\x12K\n" +
	"\x0eSysRoleRecover\x12\x1b.role.SysRoleRecoverRequest\x1a\x1c.role.SysRoleRecoverResponse\x12B\n" +
	"\vSysRoleDrop\x12\x18.role.SysRoleDropRequest\x1a\x19.role.SysRoleDropResponse\x12B\n" +
	"\vSysRoleCode\x12\x18.role.SysRoleCodeRequest\x1a\x19.role.SysRoleCodeResponse\x12B\n" +
	"\vSysRoleList\x12\x18.role.SysRoleListRequest\x1a\x19.role.SysRoleListResponse\x12M\n" +
	"\x10SysRoleListTotal\x12\x1d.role.SysRoleListTotalRequest\x1a\x1a.role.SysRoleTotalResponseB\x1dZ\x1bcloud/service/sys/role;roleb\x06proto3"

var (
	file_sys_role_proto_rawDescOnce sync.Once
	file_sys_role_proto_rawDescData []byte
)

func file_sys_role_proto_rawDescGZIP() []byte {
	file_sys_role_proto_rawDescOnce.Do(func() {
		file_sys_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_role_proto_rawDesc), len(file_sys_role_proto_rawDesc)))
	})
	return file_sys_role_proto_rawDescData
}

var file_sys_role_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_sys_role_proto_goTypes = []any{
	(*SysRoleObject)(nil),                // 0: role.SysRoleObject
	(*SysRoleTotalResponse)(nil),         // 1: role.SysRoleTotalResponse
	(*SysRoleCreateRequest)(nil),         // 2: role.SysRoleCreateRequest
	(*SysRoleCreateResponse)(nil),        // 3: role.SysRoleCreateResponse
	(*SysRoleUpdateRequest)(nil),         // 4: role.SysRoleUpdateRequest
	(*SysRoleUpdateResponse)(nil),        // 5: role.SysRoleUpdateResponse
	(*SysRoleDeleteRequest)(nil),         // 6: role.SysRoleDeleteRequest
	(*SysRoleDeleteResponse)(nil),        // 7: role.SysRoleDeleteResponse
	(*SysRoleRequest)(nil),               // 8: role.SysRoleRequest
	(*SysRoleResponse)(nil),              // 9: role.SysRoleResponse
	(*SysRoleRecoverRequest)(nil),        // 10: role.SysRoleRecoverRequest
	(*SysRoleRecoverResponse)(nil),       // 11: role.SysRoleRecoverResponse
	(*SysRoleDropRequest)(nil),           // 12: role.SysRoleDropRequest
	(*SysRoleDropResponse)(nil),          // 13: role.SysRoleDropResponse
	(*SysRoleCodeRequest)(nil),           // 14: role.SysRoleCodeRequest
	(*SysRoleCodeResponse)(nil),          // 15: role.SysRoleCodeResponse
	(*SysRoleListRequest)(nil),           // 16: role.SysRoleListRequest
	(*SysRoleListResponse)(nil),          // 17: role.SysRoleListResponse
	(*SysRoleListTotalRequest)(nil),      // 18: role.SysRoleListTotalRequest
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
	(*pagination.PaginationRequest)(nil), // 20: pagination.PaginationRequest
}
var file_sys_role_proto_depIdxs = []int32{
	19, // 0: role.SysRoleObject.create_time:type_name -> google.protobuf.Timestamp
	19, // 1: role.SysRoleObject.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: role.SysRoleCreateRequest.data:type_name -> role.SysRoleObject
	0,  // 3: role.SysRoleUpdateRequest.data:type_name -> role.SysRoleObject
	0,  // 4: role.SysRoleResponse.data:type_name -> role.SysRoleObject
	0,  // 5: role.SysRoleCodeResponse.data:type_name -> role.SysRoleObject
	20, // 6: role.SysRoleListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 7: role.SysRoleListResponse.data:type_name -> role.SysRoleObject
	2,  // 8: role.SysRoleService.SysRoleCreate:input_type -> role.SysRoleCreateRequest
	4,  // 9: role.SysRoleService.SysRoleUpdate:input_type -> role.SysRoleUpdateRequest
	6,  // 10: role.SysRoleService.SysRoleDelete:input_type -> role.SysRoleDeleteRequest
	8,  // 11: role.SysRoleService.SysRole:input_type -> role.SysRoleRequest
	10, // 12: role.SysRoleService.SysRoleRecover:input_type -> role.SysRoleRecoverRequest
	12, // 13: role.SysRoleService.SysRoleDrop:input_type -> role.SysRoleDropRequest
	14, // 14: role.SysRoleService.SysRoleCode:input_type -> role.SysRoleCodeRequest
	16, // 15: role.SysRoleService.SysRoleList:input_type -> role.SysRoleListRequest
	18, // 16: role.SysRoleService.SysRoleListTotal:input_type -> role.SysRoleListTotalRequest
	3,  // 17: role.SysRoleService.SysRoleCreate:output_type -> role.SysRoleCreateResponse
	5,  // 18: role.SysRoleService.SysRoleUpdate:output_type -> role.SysRoleUpdateResponse
	7,  // 19: role.SysRoleService.SysRoleDelete:output_type -> role.SysRoleDeleteResponse
	9,  // 20: role.SysRoleService.SysRole:output_type -> role.SysRoleResponse
	11, // 21: role.SysRoleService.SysRoleRecover:output_type -> role.SysRoleRecoverResponse
	13, // 22: role.SysRoleService.SysRoleDrop:output_type -> role.SysRoleDropResponse
	15, // 23: role.SysRoleService.SysRoleCode:output_type -> role.SysRoleCodeResponse
	17, // 24: role.SysRoleService.SysRoleList:output_type -> role.SysRoleListResponse
	1,  // 25: role.SysRoleService.SysRoleListTotal:output_type -> role.SysRoleTotalResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sys_role_proto_init() }
func file_sys_role_proto_init() {
	if File_sys_role_proto != nil {
		return
	}
	file_sys_role_proto_msgTypes[0].OneofWrappers = []any{}
	file_sys_role_proto_msgTypes[14].OneofWrappers = []any{}
	file_sys_role_proto_msgTypes[16].OneofWrappers = []any{}
	file_sys_role_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_role_proto_rawDesc), len(file_sys_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_role_proto_goTypes,
		DependencyIndexes: file_sys_role_proto_depIdxs,
		MessageInfos:      file_sys_role_proto_msgTypes,
	}.Build()
	File_sys_role_proto = out.File
	file_sys_role_proto_goTypes = nil
	file_sys_role_proto_depIdxs = nil
}
