// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: sys_user_tenant.proto

// sys_user_tenant 租户用户

package user

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SysUserTenantObject 数据对象
type SysUserTenantObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:user_id" json:"userId"
	UserId *int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"userId" gorm:"column:user_id"` //用户
	// @inject_tag: gorm:"column:tenant_id" json:"tenantId"
	TenantId      *int64 `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" gorm:"column:tenant_id"` //租户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantObject) Reset() {
	*x = SysUserTenantObject{}
	mi := &file_sys_user_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantObject) ProtoMessage() {}

func (x *SysUserTenantObject) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantObject.ProtoReflect.Descriptor instead.
func (*SysUserTenantObject) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *SysUserTenantObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SysUserTenantObject) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserTenantObject) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

// SysUserTenantTotalResponse 列表数据总量
type SysUserTenantTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantTotalResponse) Reset() {
	*x = SysUserTenantTotalResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantTotalResponse) ProtoMessage() {}

func (x *SysUserTenantTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantTotalResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantTotalResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *SysUserTenantTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserTenantTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysUserTenantCreateRequest 创建数据请求
type SysUserTenantCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SysUserTenantObject   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantCreateRequest) Reset() {
	*x = SysUserTenantCreateRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantCreateRequest) ProtoMessage() {}

func (x *SysUserTenantCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantCreateRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantCreateRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *SysUserTenantCreateRequest) GetData() *SysUserTenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserTenantCreateResponse 创建数据响应
type SysUserTenantCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantCreateResponse) Reset() {
	*x = SysUserTenantCreateResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantCreateResponse) ProtoMessage() {}

func (x *SysUserTenantCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantCreateResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantCreateResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *SysUserTenantCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserTenantCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysUserTenantUpdateRequest 更新数据请求
type SysUserTenantUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *SysUserTenantObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantUpdateRequest) Reset() {
	*x = SysUserTenantUpdateRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantUpdateRequest) ProtoMessage() {}

func (x *SysUserTenantUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantUpdateRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantUpdateRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *SysUserTenantUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysUserTenantUpdateRequest) GetData() *SysUserTenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserTenantUpdateResponse 更新数据响应
type SysUserTenantUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantUpdateResponse) Reset() {
	*x = SysUserTenantUpdateResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantUpdateResponse) ProtoMessage() {}

func (x *SysUserTenantUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantUpdateResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantUpdateResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *SysUserTenantUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysUserTenantDeleteRequest 删除数据请求
type SysUserTenantDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantDeleteRequest) Reset() {
	*x = SysUserTenantDeleteRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantDeleteRequest) ProtoMessage() {}

func (x *SysUserTenantDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantDeleteRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *SysUserTenantDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysUserTenantDeleteResponse 删除数据响应
type SysUserTenantDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantDeleteResponse) Reset() {
	*x = SysUserTenantDeleteResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantDeleteResponse) ProtoMessage() {}

func (x *SysUserTenantDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantDeleteResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantDeleteResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *SysUserTenantDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysUserTenantRequest 查询单条数据请求
type SysUserTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantRequest) Reset() {
	*x = SysUserTenantRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantRequest) ProtoMessage() {}

func (x *SysUserTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *SysUserTenantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysUserTenantResponse 查询单条数据响应
type SysUserTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysUserTenantObject   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantResponse) Reset() {
	*x = SysUserTenantResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantResponse) ProtoMessage() {}

func (x *SysUserTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *SysUserTenantResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserTenantResponse) GetData() *SysUserTenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserTenantBindRequest 查询单条数据请求
type SysUserTenantBindRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId      *int64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantBindRequest) Reset() {
	*x = SysUserTenantBindRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantBindRequest) ProtoMessage() {}

func (x *SysUserTenantBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantBindRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantBindRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *SysUserTenantBindRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserTenantBindRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

// SysUserTenantBindResponse 查询单条数据响应
type SysUserTenantBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysUserTenantObject   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantBindResponse) Reset() {
	*x = SysUserTenantBindResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantBindResponse) ProtoMessage() {}

func (x *SysUserTenantBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantBindResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantBindResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *SysUserTenantBindResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantBindResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserTenantBindResponse) GetData() *SysUserTenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserTenantListRequest 列表数据
type SysUserTenantListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantListRequest) Reset() {
	*x = SysUserTenantListRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantListRequest) ProtoMessage() {}

func (x *SysUserTenantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantListRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantListRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *SysUserTenantListRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserTenantListRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysUserTenantListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SysUserTenantListResponse 数据响应
type SysUserTenantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*SysUserTenantObject `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantListResponse) Reset() {
	*x = SysUserTenantListResponse{}
	mi := &file_sys_user_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantListResponse) ProtoMessage() {}

func (x *SysUserTenantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantListResponse.ProtoReflect.Descriptor instead.
func (*SysUserTenantListResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *SysUserTenantListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserTenantListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserTenantListResponse) GetData() []*SysUserTenantObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserTenantListTotalRequest 列表数据
type SysUserTenantListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId      *int64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserTenantListTotalRequest) Reset() {
	*x = SysUserTenantListTotalRequest{}
	mi := &file_sys_user_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserTenantListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserTenantListTotalRequest) ProtoMessage() {}

func (x *SysUserTenantListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserTenantListTotalRequest.ProtoReflect.Descriptor instead.
func (*SysUserTenantListTotalRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *SysUserTenantListTotalRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserTenantListTotalRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

var File_sys_user_tenant_proto protoreflect.FileDescriptor

const file_sys_user_tenant_proto_rawDesc = "" +
	"\n" +
	"\x15sys_user_tenant.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10pagination.proto\"\x8b\x01\n" +
	"\x13SysUserTenantObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x03 \x01(\x03H\x02R\btenantId\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_tenant_id\"V\n" +
	"\x1aSysUserTenantTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"K\n" +
	"\x1aSysUserTenantCreateRequest\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.user.SysUserTenantObjectR\x04data\"W\n" +
	"\x1bSysUserTenantCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"[\n" +
	"\x1aSysUserTenantUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x19.user.SysUserTenantObjectR\x04data\"C\n" +
	"\x1bSysUserTenantUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\",\n" +
	"\x1aSysUserTenantDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x1bSysUserTenantDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"&\n" +
	"\x14SysUserTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"l\n" +
	"\x15SysUserTenantResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.user.SysUserTenantObjectR\x04data\"t\n" +
	"\x18SysUserTenantBindRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\x03H\x01R\btenantId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_tenant_id\"p\n" +
	"\x19SysUserTenantBindResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.user.SysUserTenantObjectR\x04data\"\xc7\x01\n" +
	"\x18SysUserTenantListRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\x03H\x01R\btenantId\x88\x01\x01\x12B\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.pagination.PaginationRequestH\x02R\n" +
	"pagination\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_tenant_idB\r\n" +
	"\v_pagination\"p\n" +
	"\x19SysUserTenantListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.user.SysUserTenantObjectR\x04data\"y\n" +
	"\x1dSysUserTenantListTotalRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\x03H\x01R\btenantId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\f\n" +
	"\n" +
	"_tenant_id2\x81\x05\n" +
	"\x14SysUserTenantService\x12Z\n" +
	"\x13SysUserTenantCreate\x12 .user.SysUserTenantCreateRequest\x1a!.user.SysUserTenantCreateResponse\x12Z\n" +
	"\x13SysUserTenantUpdate\x12 .user.SysUserTenantUpdateRequest\x1a!.user.SysUserTenantUpdateResponse\x12Z\n" +
	"\x13SysUserTenantDelete\x12 .user.SysUserTenantDeleteRequest\x1a!.user.SysUserTenantDeleteResponse\x12H\n" +
	"\rSysUserTenant\x12\x1a.user.SysUserTenantRequest\x1a\x1b.user.SysUserTenantResponse\x12T\n" +
	"\x11SysUserTenantBind\x12\x1e.user.SysUserTenantBindRequest\x1a\x1f.user.SysUserTenantBindResponse\x12T\n" +
	"\x11SysUserTenantList\x12\x1e.user.SysUserTenantListRequest\x1a\x1f.user.SysUserTenantListResponse\x12_\n" +
	"\x16SysUserTenantListTotal\x12#.user.SysUserTenantListTotalRequest\x1a .user.SysUserTenantTotalResponseB\x1dZ\x1bcloud/service/sys/user;userb\x06proto3"

var (
	file_sys_user_tenant_proto_rawDescOnce sync.Once
	file_sys_user_tenant_proto_rawDescData []byte
)

func file_sys_user_tenant_proto_rawDescGZIP() []byte {
	file_sys_user_tenant_proto_rawDescOnce.Do(func() {
		file_sys_user_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_user_tenant_proto_rawDesc), len(file_sys_user_tenant_proto_rawDesc)))
	})
	return file_sys_user_tenant_proto_rawDescData
}

var file_sys_user_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sys_user_tenant_proto_goTypes = []any{
	(*SysUserTenantObject)(nil),           // 0: user.SysUserTenantObject
	(*SysUserTenantTotalResponse)(nil),    // 1: user.SysUserTenantTotalResponse
	(*SysUserTenantCreateRequest)(nil),    // 2: user.SysUserTenantCreateRequest
	(*SysUserTenantCreateResponse)(nil),   // 3: user.SysUserTenantCreateResponse
	(*SysUserTenantUpdateRequest)(nil),    // 4: user.SysUserTenantUpdateRequest
	(*SysUserTenantUpdateResponse)(nil),   // 5: user.SysUserTenantUpdateResponse
	(*SysUserTenantDeleteRequest)(nil),    // 6: user.SysUserTenantDeleteRequest
	(*SysUserTenantDeleteResponse)(nil),   // 7: user.SysUserTenantDeleteResponse
	(*SysUserTenantRequest)(nil),          // 8: user.SysUserTenantRequest
	(*SysUserTenantResponse)(nil),         // 9: user.SysUserTenantResponse
	(*SysUserTenantBindRequest)(nil),      // 10: user.SysUserTenantBindRequest
	(*SysUserTenantBindResponse)(nil),     // 11: user.SysUserTenantBindResponse
	(*SysUserTenantListRequest)(nil),      // 12: user.SysUserTenantListRequest
	(*SysUserTenantListResponse)(nil),     // 13: user.SysUserTenantListResponse
	(*SysUserTenantListTotalRequest)(nil), // 14: user.SysUserTenantListTotalRequest
	(*pagination.PaginationRequest)(nil),  // 15: pagination.PaginationRequest
}
var file_sys_user_tenant_proto_depIdxs = []int32{
	0,  // 0: user.SysUserTenantCreateRequest.data:type_name -> user.SysUserTenantObject
	0,  // 1: user.SysUserTenantUpdateRequest.data:type_name -> user.SysUserTenantObject
	0,  // 2: user.SysUserTenantResponse.data:type_name -> user.SysUserTenantObject
	0,  // 3: user.SysUserTenantBindResponse.data:type_name -> user.SysUserTenantObject
	15, // 4: user.SysUserTenantListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 5: user.SysUserTenantListResponse.data:type_name -> user.SysUserTenantObject
	2,  // 6: user.SysUserTenantService.SysUserTenantCreate:input_type -> user.SysUserTenantCreateRequest
	4,  // 7: user.SysUserTenantService.SysUserTenantUpdate:input_type -> user.SysUserTenantUpdateRequest
	6,  // 8: user.SysUserTenantService.SysUserTenantDelete:input_type -> user.SysUserTenantDeleteRequest
	8,  // 9: user.SysUserTenantService.SysUserTenant:input_type -> user.SysUserTenantRequest
	10, // 10: user.SysUserTenantService.SysUserTenantBind:input_type -> user.SysUserTenantBindRequest
	12, // 11: user.SysUserTenantService.SysUserTenantList:input_type -> user.SysUserTenantListRequest
	14, // 12: user.SysUserTenantService.SysUserTenantListTotal:input_type -> user.SysUserTenantListTotalRequest
	3,  // 13: user.SysUserTenantService.SysUserTenantCreate:output_type -> user.SysUserTenantCreateResponse
	5,  // 14: user.SysUserTenantService.SysUserTenantUpdate:output_type -> user.SysUserTenantUpdateResponse
	7,  // 15: user.SysUserTenantService.SysUserTenantDelete:output_type -> user.SysUserTenantDeleteResponse
	9,  // 16: user.SysUserTenantService.SysUserTenant:output_type -> user.SysUserTenantResponse
	11, // 17: user.SysUserTenantService.SysUserTenantBind:output_type -> user.SysUserTenantBindResponse
	13, // 18: user.SysUserTenantService.SysUserTenantList:output_type -> user.SysUserTenantListResponse
	1,  // 19: user.SysUserTenantService.SysUserTenantListTotal:output_type -> user.SysUserTenantTotalResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sys_user_tenant_proto_init() }
func file_sys_user_tenant_proto_init() {
	if File_sys_user_tenant_proto != nil {
		return
	}
	file_sys_user_tenant_proto_msgTypes[0].OneofWrappers = []any{}
	file_sys_user_tenant_proto_msgTypes[10].OneofWrappers = []any{}
	file_sys_user_tenant_proto_msgTypes[12].OneofWrappers = []any{}
	file_sys_user_tenant_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_user_tenant_proto_rawDesc), len(file_sys_user_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_user_tenant_proto_goTypes,
		DependencyIndexes: file_sys_user_tenant_proto_depIdxs,
		MessageInfos:      file_sys_user_tenant_proto_msgTypes,
	}.Build()
	File_sys_user_tenant_proto = out.File
	file_sys_user_tenant_proto_goTypes = nil
	file_sys_user_tenant_proto_depIdxs = nil
}
