// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: sys_user_dept.proto

// sys_user_dept 用户部门

package user

import (
	pagination "cloud/service/pagination"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SysUserDeptObject 数据对象
type SysUserDeptObject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"primaryKey;autoIncrement;column:id" json:"id"
	Id *int64 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id" gorm:"primaryKey;autoIncrement;column:id"` //编号
	// @inject_tag: gorm:"column:user_id" json:"userId"
	UserId *int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"userId" gorm:"column:user_id"` //用户
	// @inject_tag: gorm:"column:dept_id" json:"deptId"
	DeptId *int64 `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3,oneof" json:"deptId" gorm:"column:dept_id"` //部门
	// @inject_tag: gorm:"column:tenant_id" json:"tenantId"
	TenantId      *int64 `protobuf:"varint,4,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" gorm:"column:tenant_id"` //租户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptObject) Reset() {
	*x = SysUserDeptObject{}
	mi := &file_sys_user_dept_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptObject) ProtoMessage() {}

func (x *SysUserDeptObject) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptObject.ProtoReflect.Descriptor instead.
func (*SysUserDeptObject) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{0}
}

func (x *SysUserDeptObject) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SysUserDeptObject) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserDeptObject) GetDeptId() int64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

func (x *SysUserDeptObject) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

// SysUserDeptTotalResponse 列表数据总量
type SysUserDeptTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptTotalResponse) Reset() {
	*x = SysUserDeptTotalResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptTotalResponse) ProtoMessage() {}

func (x *SysUserDeptTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptTotalResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptTotalResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{1}
}

func (x *SysUserDeptTotalResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptTotalResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserDeptTotalResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysUserDeptCreateRequest 创建数据请求
type SysUserDeptCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SysUserDeptObject     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptCreateRequest) Reset() {
	*x = SysUserDeptCreateRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptCreateRequest) ProtoMessage() {}

func (x *SysUserDeptCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptCreateRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptCreateRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{2}
}

func (x *SysUserDeptCreateRequest) GetData() *SysUserDeptObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserDeptCreateResponse 创建数据响应
type SysUserDeptCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          int64                  `protobuf:"varint,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptCreateResponse) Reset() {
	*x = SysUserDeptCreateResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptCreateResponse) ProtoMessage() {}

func (x *SysUserDeptCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptCreateResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptCreateResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{3}
}

func (x *SysUserDeptCreateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserDeptCreateResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// SysUserDeptUpdateRequest 更新数据请求
type SysUserDeptUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	Data          *SysUserDeptObject `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptUpdateRequest) Reset() {
	*x = SysUserDeptUpdateRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptUpdateRequest) ProtoMessage() {}

func (x *SysUserDeptUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptUpdateRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptUpdateRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{4}
}

func (x *SysUserDeptUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysUserDeptUpdateRequest) GetData() *SysUserDeptObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserDeptUpdateResponse 更新数据响应
type SysUserDeptUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptUpdateResponse) Reset() {
	*x = SysUserDeptUpdateResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptUpdateResponse) ProtoMessage() {}

func (x *SysUserDeptUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptUpdateResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptUpdateResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{5}
}

func (x *SysUserDeptUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptUpdateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysUserDeptDeleteRequest 删除数据请求
type SysUserDeptDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptDeleteRequest) Reset() {
	*x = SysUserDeptDeleteRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptDeleteRequest) ProtoMessage() {}

func (x *SysUserDeptDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptDeleteRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{6}
}

func (x *SysUserDeptDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysUserDeptDeleteResponse 删除数据响应
type SysUserDeptDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptDeleteResponse) Reset() {
	*x = SysUserDeptDeleteResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptDeleteResponse) ProtoMessage() {}

func (x *SysUserDeptDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptDeleteResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptDeleteResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{7}
}

func (x *SysUserDeptDeleteResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptDeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// SysUserDeptRequest 查询单条数据请求
type SysUserDeptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: gorm:"column:id" json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id" gorm:"column:id"` //编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptRequest) Reset() {
	*x = SysUserDeptRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptRequest) ProtoMessage() {}

func (x *SysUserDeptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{8}
}

func (x *SysUserDeptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// SysUserDeptResponse 查询单条数据响应
type SysUserDeptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysUserDeptObject     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptResponse) Reset() {
	*x = SysUserDeptResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptResponse) ProtoMessage() {}

func (x *SysUserDeptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{9}
}

func (x *SysUserDeptResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserDeptResponse) GetData() *SysUserDeptObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserDeptItemRequest 查询单条数据请求
type SysUserDeptItemRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"dept_id" json:"deptId"
	DeptId        *int64 `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3,oneof" json:"deptId" db:"dept_id"` // 部门
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptItemRequest) Reset() {
	*x = SysUserDeptItemRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptItemRequest) ProtoMessage() {}

func (x *SysUserDeptItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptItemRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptItemRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{10}
}

func (x *SysUserDeptItemRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysUserDeptItemRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserDeptItemRequest) GetDeptId() int64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

// SysUserDeptItemResponse 查询单条数据响应
type SysUserDeptItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *SysUserDeptObject     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptItemResponse) Reset() {
	*x = SysUserDeptItemResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptItemResponse) ProtoMessage() {}

func (x *SysUserDeptItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptItemResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptItemResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{11}
}

func (x *SysUserDeptItemResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptItemResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserDeptItemResponse) GetData() *SysUserDeptObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserDeptListRequest 列表数据
type SysUserDeptListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"dept_id" json:"deptId"
	DeptId *int64 `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3,oneof" json:"deptId" db:"dept_id"` // 部门
	// @inject_tag: json:"pagination"
	Pagination    *pagination.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3,oneof" json:"pagination"` // 分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptListRequest) Reset() {
	*x = SysUserDeptListRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptListRequest) ProtoMessage() {}

func (x *SysUserDeptListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptListRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptListRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{12}
}

func (x *SysUserDeptListRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysUserDeptListRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserDeptListRequest) GetDeptId() int64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

func (x *SysUserDeptListRequest) GetPagination() *pagination.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// SysUserDeptListResponse 数据响应
type SysUserDeptListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*SysUserDeptObject   `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptListResponse) Reset() {
	*x = SysUserDeptListResponse{}
	mi := &file_sys_user_dept_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptListResponse) ProtoMessage() {}

func (x *SysUserDeptListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptListResponse.ProtoReflect.Descriptor instead.
func (*SysUserDeptListResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{13}
}

func (x *SysUserDeptListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserDeptListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SysUserDeptListResponse) GetData() []*SysUserDeptObject {
	if x != nil {
		return x.Data
	}
	return nil
}

// SysUserDeptListTotalRequest 列表数据
type SysUserDeptListTotalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: db:"tenant_id" json:"tenantId"
	TenantId *int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenantId" db:"tenant_id"` // 租户
	// @inject_tag: db:"user_id" json:"userId"
	UserId *int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"userId" db:"user_id"` // 用户
	// @inject_tag: db:"dept_id" json:"deptId"
	DeptId        *int64 `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3,oneof" json:"deptId" db:"dept_id"` // 部门
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysUserDeptListTotalRequest) Reset() {
	*x = SysUserDeptListTotalRequest{}
	mi := &file_sys_user_dept_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysUserDeptListTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserDeptListTotalRequest) ProtoMessage() {}

func (x *SysUserDeptListTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_dept_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserDeptListTotalRequest.ProtoReflect.Descriptor instead.
func (*SysUserDeptListTotalRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_dept_proto_rawDescGZIP(), []int{14}
}

func (x *SysUserDeptListTotalRequest) GetTenantId() int64 {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return 0
}

func (x *SysUserDeptListTotalRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SysUserDeptListTotalRequest) GetDeptId() int64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

var File_sys_user_dept_proto protoreflect.FileDescriptor

const file_sys_user_dept_proto_rawDesc = "" +
	"\n" +
	"\x13sys_user_dept.proto\x12\x04user\x1a\x10pagination.proto\"\xb3\x01\n" +
	"\x11SysUserDeptObject\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x03 \x01(\x03H\x02R\x06deptId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x04 \x01(\x03H\x03R\btenantId\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_user_idB\n" +
	"\n" +
	"\b_dept_idB\f\n" +
	"\n" +
	"_tenant_id\"T\n" +
	"\x18SysUserDeptTotalResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"G\n" +
	"\x18SysUserDeptCreateRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.user.SysUserDeptObjectR\x04data\"U\n" +
	"\x19SysUserDeptCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x03R\x04data\"W\n" +
	"\x18SysUserDeptUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.user.SysUserDeptObjectR\x04data\"A\n" +
	"\x19SysUserDeptUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"*\n" +
	"\x18SysUserDeptDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x19SysUserDeptDeleteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"$\n" +
	"\x12SysUserDeptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x13SysUserDeptResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.user.SysUserDeptObjectR\x04data\"\x9c\x01\n" +
	"\x16SysUserDeptItemRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x03 \x01(\x03H\x02R\x06deptId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_user_idB\n" +
	"\n" +
	"\b_dept_id\"l\n" +
	"\x17SysUserDeptItemResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.user.SysUserDeptObjectR\x04data\"\xef\x01\n" +
	"\x16SysUserDeptListRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x03 \x01(\x03H\x02R\x06deptId\x88\x01\x01\x12B\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1d.pagination.PaginationRequestH\x03R\n" +
	"pagination\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_user_idB\n" +
	"\n" +
	"\b_dept_idB\r\n" +
	"\v_pagination\"l\n" +
	"\x17SysUserDeptListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.user.SysUserDeptObjectR\x04data\"\xa1\x01\n" +
	"\x1bSysUserDeptListTotalRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\x03H\x00R\btenantId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x03 \x01(\x03H\x02R\x06deptId\x88\x01\x01B\f\n" +
	"\n" +
	"_tenant_idB\n" +
	"\n" +
	"\b_user_idB\n" +
	"\n" +
	"\b_dept_id2\xd5\x04\n" +
	"\x12SysUserDeptService\x12T\n" +
	"\x11SysUserDeptCreate\x12\x1e.user.SysUserDeptCreateRequest\x1a\x1f.user.SysUserDeptCreateResponse\x12T\n" +
	"\x11SysUserDeptUpdate\x12\x1e.user.SysUserDeptUpdateRequest\x1a\x1f.user.SysUserDeptUpdateResponse\x12T\n" +
	"\x11SysUserDeptDelete\x12\x1e.user.SysUserDeptDeleteRequest\x1a\x1f.user.SysUserDeptDeleteResponse\x12B\n" +
	"\vSysUserDept\x12\x18.user.SysUserDeptRequest\x1a\x19.user.SysUserDeptResponse\x12N\n" +
	"\x0fSysUserDeptItem\x12\x1c.user.SysUserDeptItemRequest\x1a\x1d.user.SysUserDeptItemResponse\x12N\n" +
	"\x0fSysUserDeptList\x12\x1c.user.SysUserDeptListRequest\x1a\x1d.user.SysUserDeptListResponse\x12Y\n" +
	"\x14SysUserDeptListTotal\x12!.user.SysUserDeptListTotalRequest\x1a\x1e.user.SysUserDeptTotalResponseB\x1dZ\x1bcloud/service/sys/user;userb\x06proto3"

var (
	file_sys_user_dept_proto_rawDescOnce sync.Once
	file_sys_user_dept_proto_rawDescData []byte
)

func file_sys_user_dept_proto_rawDescGZIP() []byte {
	file_sys_user_dept_proto_rawDescOnce.Do(func() {
		file_sys_user_dept_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sys_user_dept_proto_rawDesc), len(file_sys_user_dept_proto_rawDesc)))
	})
	return file_sys_user_dept_proto_rawDescData
}

var file_sys_user_dept_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_sys_user_dept_proto_goTypes = []any{
	(*SysUserDeptObject)(nil),            // 0: user.SysUserDeptObject
	(*SysUserDeptTotalResponse)(nil),     // 1: user.SysUserDeptTotalResponse
	(*SysUserDeptCreateRequest)(nil),     // 2: user.SysUserDeptCreateRequest
	(*SysUserDeptCreateResponse)(nil),    // 3: user.SysUserDeptCreateResponse
	(*SysUserDeptUpdateRequest)(nil),     // 4: user.SysUserDeptUpdateRequest
	(*SysUserDeptUpdateResponse)(nil),    // 5: user.SysUserDeptUpdateResponse
	(*SysUserDeptDeleteRequest)(nil),     // 6: user.SysUserDeptDeleteRequest
	(*SysUserDeptDeleteResponse)(nil),    // 7: user.SysUserDeptDeleteResponse
	(*SysUserDeptRequest)(nil),           // 8: user.SysUserDeptRequest
	(*SysUserDeptResponse)(nil),          // 9: user.SysUserDeptResponse
	(*SysUserDeptItemRequest)(nil),       // 10: user.SysUserDeptItemRequest
	(*SysUserDeptItemResponse)(nil),      // 11: user.SysUserDeptItemResponse
	(*SysUserDeptListRequest)(nil),       // 12: user.SysUserDeptListRequest
	(*SysUserDeptListResponse)(nil),      // 13: user.SysUserDeptListResponse
	(*SysUserDeptListTotalRequest)(nil),  // 14: user.SysUserDeptListTotalRequest
	(*pagination.PaginationRequest)(nil), // 15: pagination.PaginationRequest
}
var file_sys_user_dept_proto_depIdxs = []int32{
	0,  // 0: user.SysUserDeptCreateRequest.data:type_name -> user.SysUserDeptObject
	0,  // 1: user.SysUserDeptUpdateRequest.data:type_name -> user.SysUserDeptObject
	0,  // 2: user.SysUserDeptResponse.data:type_name -> user.SysUserDeptObject
	0,  // 3: user.SysUserDeptItemResponse.data:type_name -> user.SysUserDeptObject
	15, // 4: user.SysUserDeptListRequest.pagination:type_name -> pagination.PaginationRequest
	0,  // 5: user.SysUserDeptListResponse.data:type_name -> user.SysUserDeptObject
	2,  // 6: user.SysUserDeptService.SysUserDeptCreate:input_type -> user.SysUserDeptCreateRequest
	4,  // 7: user.SysUserDeptService.SysUserDeptUpdate:input_type -> user.SysUserDeptUpdateRequest
	6,  // 8: user.SysUserDeptService.SysUserDeptDelete:input_type -> user.SysUserDeptDeleteRequest
	8,  // 9: user.SysUserDeptService.SysUserDept:input_type -> user.SysUserDeptRequest
	10, // 10: user.SysUserDeptService.SysUserDeptItem:input_type -> user.SysUserDeptItemRequest
	12, // 11: user.SysUserDeptService.SysUserDeptList:input_type -> user.SysUserDeptListRequest
	14, // 12: user.SysUserDeptService.SysUserDeptListTotal:input_type -> user.SysUserDeptListTotalRequest
	3,  // 13: user.SysUserDeptService.SysUserDeptCreate:output_type -> user.SysUserDeptCreateResponse
	5,  // 14: user.SysUserDeptService.SysUserDeptUpdate:output_type -> user.SysUserDeptUpdateResponse
	7,  // 15: user.SysUserDeptService.SysUserDeptDelete:output_type -> user.SysUserDeptDeleteResponse
	9,  // 16: user.SysUserDeptService.SysUserDept:output_type -> user.SysUserDeptResponse
	11, // 17: user.SysUserDeptService.SysUserDeptItem:output_type -> user.SysUserDeptItemResponse
	13, // 18: user.SysUserDeptService.SysUserDeptList:output_type -> user.SysUserDeptListResponse
	1,  // 19: user.SysUserDeptService.SysUserDeptListTotal:output_type -> user.SysUserDeptTotalResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sys_user_dept_proto_init() }
func file_sys_user_dept_proto_init() {
	if File_sys_user_dept_proto != nil {
		return
	}
	file_sys_user_dept_proto_msgTypes[0].OneofWrappers = []any{}
	file_sys_user_dept_proto_msgTypes[10].OneofWrappers = []any{}
	file_sys_user_dept_proto_msgTypes[12].OneofWrappers = []any{}
	file_sys_user_dept_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sys_user_dept_proto_rawDesc), len(file_sys_user_dept_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_user_dept_proto_goTypes,
		DependencyIndexes: file_sys_user_dept_proto_depIdxs,
		MessageInfos:      file_sys_user_dept_proto_msgTypes,
	}.Build()
	File_sys_user_dept_proto = out.File
	file_sys_user_dept_proto_goTypes = nil
	file_sys_user_dept_proto_depIdxs = nil
}
