// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: sys_user_role.proto

// sys_user_role 用户角色

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysUserRoleService_SysUserRoleCreate_FullMethodName    = "/user.SysUserRoleService/SysUserRoleCreate"
	SysUserRoleService_SysUserRoleUpdate_FullMethodName    = "/user.SysUserRoleService/SysUserRoleUpdate"
	SysUserRoleService_SysUserRoleDelete_FullMethodName    = "/user.SysUserRoleService/SysUserRoleDelete"
	SysUserRoleService_SysUserRole_FullMethodName          = "/user.SysUserRoleService/SysUserRole"
	SysUserRoleService_SysUserRoleItem_FullMethodName      = "/user.SysUserRoleService/SysUserRoleItem"
	SysUserRoleService_SysUserRoleList_FullMethodName      = "/user.SysUserRoleService/SysUserRoleList"
	SysUserRoleService_SysUserRoleListTotal_FullMethodName = "/user.SysUserRoleService/SysUserRoleListTotal"
)

// SysUserRoleServiceClient is the client API for SysUserRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysUserRoleService 服务
type SysUserRoleServiceClient interface {
	SysUserRoleCreate(ctx context.Context, in *SysUserRoleCreateRequest, opts ...grpc.CallOption) (*SysUserRoleCreateResponse, error)
	SysUserRoleUpdate(ctx context.Context, in *SysUserRoleUpdateRequest, opts ...grpc.CallOption) (*SysUserRoleUpdateResponse, error)
	SysUserRoleDelete(ctx context.Context, in *SysUserRoleDeleteRequest, opts ...grpc.CallOption) (*SysUserRoleDeleteResponse, error)
	SysUserRole(ctx context.Context, in *SysUserRoleRequest, opts ...grpc.CallOption) (*SysUserRoleResponse, error)
	SysUserRoleItem(ctx context.Context, in *SysUserRoleItemRequest, opts ...grpc.CallOption) (*SysUserRoleItemResponse, error)
	SysUserRoleList(ctx context.Context, in *SysUserRoleListRequest, opts ...grpc.CallOption) (*SysUserRoleListResponse, error)
	SysUserRoleListTotal(ctx context.Context, in *SysUserRoleListTotalRequest, opts ...grpc.CallOption) (*SysUserRoleTotalResponse, error)
}

type sysUserRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysUserRoleServiceClient(cc grpc.ClientConnInterface) SysUserRoleServiceClient {
	return &sysUserRoleServiceClient{cc}
}

func (c *sysUserRoleServiceClient) SysUserRoleCreate(ctx context.Context, in *SysUserRoleCreateRequest, opts ...grpc.CallOption) (*SysUserRoleCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleCreateResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRoleUpdate(ctx context.Context, in *SysUserRoleUpdateRequest, opts ...grpc.CallOption) (*SysUserRoleUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleUpdateResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRoleDelete(ctx context.Context, in *SysUserRoleDeleteRequest, opts ...grpc.CallOption) (*SysUserRoleDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleDeleteResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRole(ctx context.Context, in *SysUserRoleRequest, opts ...grpc.CallOption) (*SysUserRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRoleItem(ctx context.Context, in *SysUserRoleItemRequest, opts ...grpc.CallOption) (*SysUserRoleItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleItemResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRoleList(ctx context.Context, in *SysUserRoleListRequest, opts ...grpc.CallOption) (*SysUserRoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleListResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserRoleServiceClient) SysUserRoleListTotal(ctx context.Context, in *SysUserRoleListTotalRequest, opts ...grpc.CallOption) (*SysUserRoleTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserRoleTotalResponse)
	err := c.cc.Invoke(ctx, SysUserRoleService_SysUserRoleListTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysUserRoleServiceServer is the server API for SysUserRoleService service.
// All implementations must embed UnimplementedSysUserRoleServiceServer
// for forward compatibility.
//
// SysUserRoleService 服务
type SysUserRoleServiceServer interface {
	SysUserRoleCreate(context.Context, *SysUserRoleCreateRequest) (*SysUserRoleCreateResponse, error)
	SysUserRoleUpdate(context.Context, *SysUserRoleUpdateRequest) (*SysUserRoleUpdateResponse, error)
	SysUserRoleDelete(context.Context, *SysUserRoleDeleteRequest) (*SysUserRoleDeleteResponse, error)
	SysUserRole(context.Context, *SysUserRoleRequest) (*SysUserRoleResponse, error)
	SysUserRoleItem(context.Context, *SysUserRoleItemRequest) (*SysUserRoleItemResponse, error)
	SysUserRoleList(context.Context, *SysUserRoleListRequest) (*SysUserRoleListResponse, error)
	SysUserRoleListTotal(context.Context, *SysUserRoleListTotalRequest) (*SysUserRoleTotalResponse, error)
	mustEmbedUnimplementedSysUserRoleServiceServer()
}

// UnimplementedSysUserRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysUserRoleServiceServer struct{}

func (UnimplementedSysUserRoleServiceServer) SysUserRoleCreate(context.Context, *SysUserRoleCreateRequest) (*SysUserRoleCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleCreate not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRoleUpdate(context.Context, *SysUserRoleUpdateRequest) (*SysUserRoleUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleUpdate not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRoleDelete(context.Context, *SysUserRoleDeleteRequest) (*SysUserRoleDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleDelete not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRole(context.Context, *SysUserRoleRequest) (*SysUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRole not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRoleItem(context.Context, *SysUserRoleItemRequest) (*SysUserRoleItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleItem not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRoleList(context.Context, *SysUserRoleListRequest) (*SysUserRoleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleList not implemented")
}
func (UnimplementedSysUserRoleServiceServer) SysUserRoleListTotal(context.Context, *SysUserRoleListTotalRequest) (*SysUserRoleTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysUserRoleListTotal not implemented")
}
func (UnimplementedSysUserRoleServiceServer) mustEmbedUnimplementedSysUserRoleServiceServer() {}
func (UnimplementedSysUserRoleServiceServer) testEmbeddedByValue()                            {}

// UnsafeSysUserRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysUserRoleServiceServer will
// result in compilation errors.
type UnsafeSysUserRoleServiceServer interface {
	mustEmbedUnimplementedSysUserRoleServiceServer()
}

func RegisterSysUserRoleServiceServer(s grpc.ServiceRegistrar, srv SysUserRoleServiceServer) {
	// If the following call pancis, it indicates UnimplementedSysUserRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysUserRoleService_ServiceDesc, srv)
}

func _SysUserRoleService_SysUserRoleCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleCreate(ctx, req.(*SysUserRoleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRoleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleUpdate(ctx, req.(*SysUserRoleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRoleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleDelete(ctx, req.(*SysUserRoleDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRole(ctx, req.(*SysUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRoleItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleItem(ctx, req.(*SysUserRoleItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleList(ctx, req.(*SysUserRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserRoleService_SysUserRoleListTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserRoleListTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserRoleServiceServer).SysUserRoleListTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserRoleService_SysUserRoleListTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserRoleServiceServer).SysUserRoleListTotal(ctx, req.(*SysUserRoleListTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysUserRoleService_ServiceDesc is the grpc.ServiceDesc for SysUserRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysUserRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.SysUserRoleService",
	HandlerType: (*SysUserRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysUserRoleCreate",
			Handler:    _SysUserRoleService_SysUserRoleCreate_Handler,
		},
		{
			MethodName: "SysUserRoleUpdate",
			Handler:    _SysUserRoleService_SysUserRoleUpdate_Handler,
		},
		{
			MethodName: "SysUserRoleDelete",
			Handler:    _SysUserRoleService_SysUserRoleDelete_Handler,
		},
		{
			MethodName: "SysUserRole",
			Handler:    _SysUserRoleService_SysUserRole_Handler,
		},
		{
			MethodName: "SysUserRoleItem",
			Handler:    _SysUserRoleService_SysUserRoleItem_Handler,
		},
		{
			MethodName: "SysUserRoleList",
			Handler:    _SysUserRoleService_SysUserRoleList_Handler,
		},
		{
			MethodName: "SysUserRoleListTotal",
			Handler:    _SysUserRoleService_SysUserRoleListTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_user_role.proto",
}
