// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: sys_user_post.proto

// sys_user_post 用户职位

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysUserPostService_SysUserPostCreate_FullMethodName    = "/user.SysUserPostService/SysUserPostCreate"
	SysUserPostService_SysUserPostUpdate_FullMethodName    = "/user.SysUserPostService/SysUserPostUpdate"
	SysUserPostService_SysUserPostDelete_FullMethodName    = "/user.SysUserPostService/SysUserPostDelete"
	SysUserPostService_SysUserPost_FullMethodName          = "/user.SysUserPostService/SysUserPost"
	SysUserPostService_SysUserPostItem_FullMethodName      = "/user.SysUserPostService/SysUserPostItem"
	SysUserPostService_SysUserPostList_FullMethodName      = "/user.SysUserPostService/SysUserPostList"
	SysUserPostService_SysUserPostListTotal_FullMethodName = "/user.SysUserPostService/SysUserPostListTotal"
)

// SysUserPostServiceClient is the client API for SysUserPostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SysUserPostService 服务
type SysUserPostServiceClient interface {
	SysUserPostCreate(ctx context.Context, in *SysUserPostCreateRequest, opts ...grpc.CallOption) (*SysUserPostCreateResponse, error)
	SysUserPostUpdate(ctx context.Context, in *SysUserPostUpdateRequest, opts ...grpc.CallOption) (*SysUserPostUpdateResponse, error)
	SysUserPostDelete(ctx context.Context, in *SysUserPostDeleteRequest, opts ...grpc.CallOption) (*SysUserPostDeleteResponse, error)
	SysUserPost(ctx context.Context, in *SysUserPostRequest, opts ...grpc.CallOption) (*SysUserPostResponse, error)
	SysUserPostItem(ctx context.Context, in *SysUserPostItemRequest, opts ...grpc.CallOption) (*SysUserPostItemResponse, error)
	SysUserPostList(ctx context.Context, in *SysUserPostListRequest, opts ...grpc.CallOption) (*SysUserPostListResponse, error)
	SysUserPostListTotal(ctx context.Context, in *SysUserPostListTotalRequest, opts ...grpc.CallOption) (*SysUserPostTotalResponse, error)
}

type sysUserPostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysUserPostServiceClient(cc grpc.ClientConnInterface) SysUserPostServiceClient {
	return &sysUserPostServiceClient{cc}
}

func (c *sysUserPostServiceClient) SysUserPostCreate(ctx context.Context, in *SysUserPostCreateRequest, opts ...grpc.CallOption) (*SysUserPostCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostCreateResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPostUpdate(ctx context.Context, in *SysUserPostUpdateRequest, opts ...grpc.CallOption) (*SysUserPostUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostUpdateResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPostDelete(ctx context.Context, in *SysUserPostDeleteRequest, opts ...grpc.CallOption) (*SysUserPostDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostDeleteResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPost(ctx context.Context, in *SysUserPostRequest, opts ...grpc.CallOption) (*SysUserPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPostItem(ctx context.Context, in *SysUserPostItemRequest, opts ...grpc.CallOption) (*SysUserPostItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostItemResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPostList(ctx context.Context, in *SysUserPostListRequest, opts ...grpc.CallOption) (*SysUserPostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostListResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysUserPostServiceClient) SysUserPostListTotal(ctx context.Context, in *SysUserPostListTotalRequest, opts ...grpc.CallOption) (*SysUserPostTotalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysUserPostTotalResponse)
	err := c.cc.Invoke(ctx, SysUserPostService_SysUserPostListTotal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysUserPostServiceServer is the server API for SysUserPostService service.
// All implementations must embed UnimplementedSysUserPostServiceServer
// for forward compatibility.
//
// SysUserPostService 服务
type SysUserPostServiceServer interface {
	SysUserPostCreate(context.Context, *SysUserPostCreateRequest) (*SysUserPostCreateResponse, error)
	SysUserPostUpdate(context.Context, *SysUserPostUpdateRequest) (*SysUserPostUpdateResponse, error)
	SysUserPostDelete(context.Context, *SysUserPostDeleteRequest) (*SysUserPostDeleteResponse, error)
	SysUserPost(context.Context, *SysUserPostRequest) (*SysUserPostResponse, error)
	SysUserPostItem(context.Context, *SysUserPostItemRequest) (*SysUserPostItemResponse, error)
	SysUserPostList(context.Context, *SysUserPostListRequest) (*SysUserPostListResponse, error)
	SysUserPostListTotal(context.Context, *SysUserPostListTotalRequest) (*SysUserPostTotalResponse, error)
	mustEmbedUnimplementedSysUserPostServiceServer()
}

// UnimplementedSysUserPostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysUserPostServiceServer struct{}

func (UnimplementedSysUserPostServiceServer) SysUserPostCreate(context.Context, *SysUserPostCreateRequest) (*SysUserPostCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostCreate not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPostUpdate(context.Context, *SysUserPostUpdateRequest) (*SysUserPostUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostUpdate not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPostDelete(context.Context, *SysUserPostDeleteRequest) (*SysUserPostDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostDelete not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPost(context.Context, *SysUserPostRequest) (*SysUserPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPost not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPostItem(context.Context, *SysUserPostItemRequest) (*SysUserPostItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostItem not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPostList(context.Context, *SysUserPostListRequest) (*SysUserPostListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostList not implemented")
}
func (UnimplementedSysUserPostServiceServer) SysUserPostListTotal(context.Context, *SysUserPostListTotalRequest) (*SysUserPostTotalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SysUserPostListTotal not implemented")
}
func (UnimplementedSysUserPostServiceServer) mustEmbedUnimplementedSysUserPostServiceServer() {}
func (UnimplementedSysUserPostServiceServer) testEmbeddedByValue()                            {}

// UnsafeSysUserPostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysUserPostServiceServer will
// result in compilation errors.
type UnsafeSysUserPostServiceServer interface {
	mustEmbedUnimplementedSysUserPostServiceServer()
}

func RegisterSysUserPostServiceServer(s grpc.ServiceRegistrar, srv SysUserPostServiceServer) {
	// If the following call panics, it indicates UnimplementedSysUserPostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysUserPostService_ServiceDesc, srv)
}

func _SysUserPostService_SysUserPostCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostCreate(ctx, req.(*SysUserPostCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPostUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostUpdate(ctx, req.(*SysUserPostUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPostDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostDelete(ctx, req.(*SysUserPostDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPost(ctx, req.(*SysUserPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPostItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostItem(ctx, req.(*SysUserPostItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostList(ctx, req.(*SysUserPostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysUserPostService_SysUserPostListTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysUserPostListTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysUserPostServiceServer).SysUserPostListTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysUserPostService_SysUserPostListTotal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysUserPostServiceServer).SysUserPostListTotal(ctx, req.(*SysUserPostListTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysUserPostService_ServiceDesc is the grpc.ServiceDesc for SysUserPostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysUserPostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.SysUserPostService",
	HandlerType: (*SysUserPostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SysUserPostCreate",
			Handler:    _SysUserPostService_SysUserPostCreate_Handler,
		},
		{
			MethodName: "SysUserPostUpdate",
			Handler:    _SysUserPostService_SysUserPostUpdate_Handler,
		},
		{
			MethodName: "SysUserPostDelete",
			Handler:    _SysUserPostService_SysUserPostDelete_Handler,
		},
		{
			MethodName: "SysUserPost",
			Handler:    _SysUserPostService_SysUserPost_Handler,
		},
		{
			MethodName: "SysUserPostItem",
			Handler:    _SysUserPostService_SysUserPostItem_Handler,
		},
		{
			MethodName: "SysUserPostList",
			Handler:    _SysUserPostService_SysUserPostList_Handler,
		},
		{
			MethodName: "SysUserPostListTotal",
			Handler:    _SysUserPostService_SysUserPostListTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sys_user_post.proto",
}
